### ISSUE TITLE
Write methodology part

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015-GECCO-MADE#10]
What you talked about with @raiben

**Comment by fergunet** [comment]
Note: I am actually writing the experimental setup, as the methodology part is being written by @raiben

**Comment by JJ** [comment]
OK. Don't forget to name somebody to review when you're done.

2015-01-30 20:55 GMT+01:00 Pablo García Sánchez notifications@github.com:

> Note: I am actually writing the experimental setup, as the methodology
> part is being written by @raiben https://github.com/raiben
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-GECCO-MADE/issues/10#issuecomment-72260414
> .

## 

JJ
