### ISSUE TITLE
Puntos a tratar y temática

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#12]
Reenfocamos el paper para
- Analizar formalmente los arquetipos presentes en el monomito 
- Reformular el modelo EC-ABM según la atquitectura propuesta https://github.com/geneura-papers/2015-MADE-MONOMITH/raw/master/imags/methodology_layers.pdf
- Rediseñar los agentes según el análisis formal de arquetipos
- Implementar las 3 funciones fitness
- Lanzar experimentos y analizar resultados
- Incluir una historia generada

La arquitectura de la investigación contiene los siguientes puntos:
1.- El monomito
2.- Análisis formal de los arquetipos
3.- Predicados base
4.- Se integra en nuestro modelo EC-ABM (3 capas)
5.- Capa 1:
    Nuestros agentes eran limitados: Nuevo diseño
    Acciones que cumplan los predicados base
    Representar el autómata
    Cada transición tiene una probabilidad
6.- Capa 2:
    Interfaz de predicados base
7.- Capa 3:
    las 3 funciones fitness
    Comparación
8.- Generación de historia

Si tenéis cualquier objeción o nota (@fergunet, @amorag, @JJ y @mgarenas) indicadlo en este hilo. Si no, procederé a ampliar cada punto y a crear issues.
@amorag, ¿Podrías repetirme qué formato de paper íbamos a adoptar ahora?
He pedido ayuda a una posible colaboradora Doctora en Filosofía, experta en predicados lógicos y lenguaje natural. Creo que podrá aportar en la formalización de los arquetipos y el paso de generación de historias. Pendiente de respuesta.

**Comment by amorag** [comment]
Me parece todo bien. ;)

Si vamos a apuntar a la IEEE Transactions on Computational Intelligence and AI in Games, el formato es el que acabo de subir a GitHub. 

Vamos palante. :D

De: Rubén Héctor [mailto:notifications@github.com] 
Enviado el: domingo, 8 de febrero de 2015 17:39
Para: geneura-papers/2015-MADE-MONOMITH
CC: Antonio Mora
Asunto: [2015-MADE-MONOMITH] Estructura del paper (#12)

Reenfocamos el paper para
-   Analizar formalmente los arquetipos presentes en el monomito 
-   Reformular el modelo EC-ABM según la atquitectura propuesta https://github.com/geneura-papers/2015-MADE-MONOMITH/raw/master/imags/methodology_layers.pdf 
-   Rediseñar los agentes según el análisis formal de arquetipos
-   Implementar las 3 funciones fitness
-   Lanzar experimentos y analizar resultados
-   Incluir una historia generada

La arquitectura de la investigación contiene los siguientes puntos:
1.- El monomito
2.- Análisis formal de los arquetipos
3.- Predicados base
4.- Se integra en nuestro modelo EC-ABM (3 capas)
5.- Capa 1:
Nuestros agentes eran limitados: Nuevo diseño
Acciones que cumplan los predicados base
Representar el autómata
Cada transición tiene una probabilidad
6.- Capa 2:
Interfaz de predicados base
7.- Capa 3:
las 3 funciones fitness
Comparación
8.- Generación de historia

Si tenéis cualquier objeción o nota (@fergunet https://github.com/fergunet , @amorag https://github.com/amorag , @JJ https://github.com/JJ  y @mgarenas https://github.com/mgarenas ) indicadlo en este hilo. Si no, procederé a ampliar cada punto y a crear issues.
@amorag https://github.com/amorag , ¿Podrías repetirme qué formato de paper íbamos a adoptar ahora?
He pedido ayuda a una posible colaboradora Doctora en Filosofía, experta en predicados lógicos y lenguaje natural. Creo que podrá aportar en la formalización de los arquetipos y el paso de generación de historias. Pendiente de respuesta.

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2015-MADE-MONOMITH/issues/12 .  https://github.com/notifications/beacon/AC6-WoR78VS36yHzzNAixFOY3KYmA6Uzks5np4isgaJpZM4DdZdE.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4281/9073 - Fecha de publicación: 02/07/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4273/9028 - Fecha de publicación: 01/30/15
Base de datos de virus interno no está actualizado.

**Comment by JJ** [comment]
Me parece bien, pero plantea una serie de hitos con fechas concretas para no extendernos demasiado en el tiempo. Reformula o cierra los issues que hay hasta ahora.

**Comment by mgarenas** [comment]
Bien, creo que ahora la idea está bastante más madura, que inicialmente, cualquier IEEE es complicado así que hay que intentar tapar todos los huecos.

Maribel

**Comment by rhgarcia** [comment]
Doy por cerrado este punto
