### ISSUE TITLE
Nuevo formato de paper para el IEEE

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#13]
Subir nueva plantilla y cambiar los script de compilación para que se use el nuevo fichero, bibliogrfía, etc.

**Comment by amorag** [comment]
En GitHub puse la nueva plantilla y pasé el artículo del GECCO al formato de la revista. ;)

Por si no lo vísteis. :D

De: Rubén Héctor [mailto:notifications@github.com] 
Enviado el: domingo, 15 de febrero de 2015 17:53
Para: geneura-papers/2015-MADE-MONOMITH
Asunto: [2015-MADE-MONOMITH] Nuevo formato de paper para el IEEE (#13)

Subir nueva plantilla y cambiar los script de compilación para que se use el nuevo fichero, bibliogrfía, etc.

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2015-MADE-MONOMITH/issues/13 .  https://github.com/notifications/beacon/AC6-Wv9Q9CvB7WbXDcRwpOJkk1mJ8hKvks5nsMZygaJpZM4DgsIa.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4284/9118 - Fecha de publicación: 02/15/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4284/9100 - Fecha de publicación: 02/12/15

**Comment by rhgarcia** [comment]
Ok :-)
me asigno la revisión

**Comment by rhgarcia** [comment]
Vale, todo estaba ok salvo el script "compilar".
Lo he arreglado yo mismo :+1:

**Comment by JJ** [comment]
close via commit always!!!

2015-02-22 19:37 GMT+01:00 Rubén Héctor García notifications@github.com:

> Closed #13
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/13.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/13#event-239792547
> .

## 

JJ

**Comment by rhgarcia** [comment]
Actualizado el formato, de manera que el espacio para el contenido es exactamente el mismo que antes pero los comentarios ya no estan en línea, sino en los bordes, y por lo tanto la página como tal ocupa más (Así los comentarios no afectan al tamaño o maquetación del paper).
Para ver cómo queda, https://dl.dropboxusercontent.com/u/31548036/made_tociaig_example.pdf
PD: Ojo, antes de enviar habrá que borrar el código indicado en el TODO.

**Comment by JJ** [comment]
Cool!
Algún día, todos los papers se harán así...
