### ISSUE TITLE
Grooming de requisitos...

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#14]
Se acordó tratar los siguientes temas en la metodología. La idea es desmigar cada punto a tratar para evitar que se quede algún tema pendiente cuando se comience a tratar con la metodología.

El grooming debería finalizarse antes del **22 de Febrero**. Por favor, quien quiera aportar algo al grooming, que lo haga en este hilo :-)
Estáis todos invitados: @JJ, @amorag, @fergunet, @mgarenas y los demás.
Por ejemplo: _"el punto 1 debe tener en cuenta el paper AAAAA ya que parece interesante", "el punto 10 debería definir estos parámetros", "el punto 10 debería mostrar una tabla con los parámetros XXX", "Creo que falta un punto para hablar de YYY"_, etc.

0.- Abstract
1.- SOTA (ponía por error SOA)
2.- El monomito
3.- Análisis formal de los arquetipos
4.- Predicados base
5.- Se integra en nuestro modelo EC-ABM (3 capas)
6.- Capa 1:
  6.1.- Nuestros agentes eran limitados: Nuevo diseño
  6.2.- Acciones que cumplan los predicados base
  6.3.- Representar el autómata
  6.4.- Cada transición tiene una probabilidad
7.- Capa 2:
  7.1.- Interfaz de predicados base
8.- Capa 3:
  8.1.- las 3 funciones fitness
  8.2.- Comparación
9.- Generación de historia
10.- Experimental setup
11.- Resultados
12.- Conclusiones

**Comment by JJ** [comment]
SOA no debería ir en primer lugar, de hecho no sé muy bien qué hace ahí... En algún momento tienes que comentar el trabajo hecho hasta ahora y ponerlo como un avance hasta el momento actual. El punto 9, generación de la historia, en realidad debería tener mucha más importancia. Lo estamos dejando al final y puede darnos problemas. 8.1, no menciones un número de funciones determinada. Serán las que tengan que ser.
Quizás @unintendedbear puede aportar también algo, o @deantares

**Comment by amorag** [comment]
JJ, la generación de la historia no tiene mucho peso en este artículo.

Al menos eso hablamos Rubén, Fergu y yo.

Más que nada porque ésta se generará ‘a manubrio’.

En futuros artículos se podría (y supongo que se hará) plantear la ‘automatización’ de dicha escritura. ;)

Este trabajo presenta el modelado del monomito de forma efectiva, así como la estructura en capas para la aplicación de un EA a nivel del ‘mundo’, para obtener un conjunto de predicados y relaciones entre ellos, que se puedan traducir en una historia.

O algo así, que yo ya me pierdo en estos berenjenales literarios. XD

Rubén, falta una intro en la que contar lo que comenta JJ de los trabajos anteriores y la estructura general de éste.

Ponla en lugar o a continuación del abstract.

Ánimo y adelante. ;)

De: Juan Julián Merelo Guervós [mailto:notifications@github.com] 
Enviado el: domingo, 15 de febrero de 2015 19:48
Para: geneura-papers/2015-MADE-MONOMITH
CC: Antonio Mora
Asunto: Re: [2015-MADE-MONOMITH] Grooming de requisitos... (#14)

SOA no debería ir en primer lugar, de hecho no sé muy bien qué hace ahí... En algún momento tienes que comentar el trabajo hecho hasta ahora y ponerlo como un avance hasta el momento actual. El punto 9, generación de la historia, en realidad debería tener mucha más importancia. Lo estamos dejando al final y puede darnos problemas. 8.1, no menciones un número de funciones determinada. Serán las que tengan que ser.
Quizás @unintendedbear https://github.com/unintendedbear  puede aportar también algo, o @deantares https://github.com/deantares  

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2015-MADE-MONOMITH/issues/14#issuecomment-74430584 .  https://github.com/notifications/beacon/AC6-WlTSKHP8YSON52UtrNTbwXiJO8IEks5nsOF4gaJpZM4DgsRR.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4284/9118 - Fecha de publicación: 02/15/15

**Comment by rhgarcia** [comment]
@JJ perdona, puse SOA y quería escribir SOTA xD, estoy tonto

**Comment by mgarenas** [comment]
Me pregunto, sólo me pregunto, si en el punto de predicados base debería irse desarrollando a la vez que los arquetipos formales, vamos... que si a la vez que vas introduciendo los arquetipos, podrías ir introduciendo los predicados relacionados con ellos para que sea más entendible y conexo. De todas formas podéis decirme tranquilamente que estoy diciendo una solemne tontería :-)

**Comment by pacastillo** [comment]
¿La generación de la historia influye en el resto de elementos, o es el funcionamiento-diseño de los demás elementos lo que determinan cómo se genera la historia?

El experimental setup habría que detallarlo, indicando qué experimentos se llevarán a cabo y cómo.

Una curiosidad, ¿SOTA es el State Of The Art?

**Comment by unintendedbear** [comment]
> Una curiosidad, ¿SOTA es el State Of The Art?

Sí, @pacastillo .
Seguramente es una pregunta muy tonta, pero, ¿hay alguna razón para que sea Monomith y no Monomyth?

Si la generación de la historia no tiene mucho peso pero la queréis automatizar más adelante, recordad comentarlo en trabajo futuro. Que por cierto no hay sección de trabajo futuro, podría ponerse junto con las conclusiones.

**Comment by rhgarcia** [comment]
Genial, reviso de nuevo todos los comentarios y cierro la estructura final. Muchas gracias a todos por los comentarios :-)

**Comment by rhgarcia** [comment]
Hola, aquí la estructura del trabajo con vuestros comentarios incorporados. Muchas gracias a todos:

ABSTRACT
0.- Abstract

ESTADO DEL ARTE
1.- Estado del arte
1.1.- Incluir el trabajo hecho hasta ahora

METODOLOGÍA
2.- El monomito
3.- Análisis formal de los arquetipos y predicados base
4.- (Fusionado)
5.- Se integra en nuestro modelo EC-ABM (3 capas)
6.- Capa 1:
6.1.- Nuestros agentes eran limitados: Nuevo diseño
6.2.- Acciones que cumplan los predicados base
6.3.- Representar el autómata
6.4.- Cada transición tiene una probabilidad
7.- Capa 2:
7.1.- Interfaz de predicados base
8.- Capa 3:
8.1.- las 3 funciones fitness
8.2.- Comparación
9.- Generación de historias

EXPERIMENTAL SETUP
10.- Experimental setup
10.1.- Qué experimentos se realizarán y cómo
10.2.- Qué análisis se realziarán

RESULTADOS
11.- Resultados

CONCLUSIONES
12.- Conclusiones

Voy respondiendo a los comentarios también:

_@JJ : SOA no debería ir en primer lugar, de hecho no sé muy bien qué hace ahí... En algún momento tienes que comentar el trabajo hecho hasta ahora y ponerlo como un avance hasta el momento actual._
Exacto, puse "SOA" por equivocación. Añado además en el punto la nota de añadir el trabajo hecho hasta ahora

_@JJ: El punto 9, generación de la historia, en realidad debería tener mucha más importancia. Lo estamos dejando al final y puede darnos problemas._
Ok. Respondiéndote a tí y a @amorag, es cierto que vamos a ir pensando en generar historias pero no se si debe ser el peso del paper. Yo lo pondría como un objetivo secundario. De hecho Arancha tambien iba a darle una vuelta. Esta estructura es una estructura de temas a tratar en el paper y, aunque se muestre en el punto 9, es parte de la metodología, que es lo primero que vamos a abordar.

_@JJ: 8.1, no menciones un número de funciones determinada. Serán las que tengan que ser._
Ok, estre este sprint y el siguiente deberíamos cerrar número y explicarlas, ya que comenzará el experimental setup y las ejecuciónes.

_@mgarenas:  Me pregunto, sólo me pregunto, si en el punto de predicados base debería irse desarrollando a la vez que los arquetipos formales, vamos... que si a la vez que vas introduciendo los arquetipos, podrías ir introduciendo los predicados relacionados con ellos para que sea más entendible y conexo. De todas formas podéis decirme tranquilamente que estoy diciendo una solemne tontería :-)"_
En absoluto es una tontería. Si para nosotros queda lioso, para un revisor ni te cuento. Habrá que buscar el equilibrio entre formalismo y claridad. Veo bien lo qu comentas. Podemos hacerlo de manera que cada arquetipo introducido explique los predicados asociados. Lo vamos viendo y revisando para dejarlo ben pulido. Fusiono los puntos 3 y 4.

_@pacastillo:  ¿La generación de la historia influye en el resto de elementos, o es el funcionamiento-diseño de los demás elementos lo que determinan cómo se genera la historia?"_
Supongo que ambas cosas a la vez: El funcionamiento-diseño de mundo y personajes determinan las historias, pero son parametrizables, así que un GA guíará la solución que mejores historias genere.

_@pacastillo: El experimental setup habría que detallarlo, indicando qué experimentos se llevarán a cabo y cómo._
Sí, creo que es elgo que habrá que detallar este sprint. Ahí me tendréis que echar una mano :-) . Añado dos subpuntos al punto 10.

**Comment by amorag** [comment]
Rubén, después del abstract falta la introducción. ;)
En la que presentes el problema y plantees a modo de resumen lo que va a presentar el artículo.
Aquí se suele hablar de los trabajos previos y justificar el por qué de este.

Después iría el SotA, con la comparativa de este trabajo con lo que existe en la bibliografía.

Creo que no entendiste mi comentario, porque le respondí a JJ lo mismo que dices tú, que en este artículo la generación de la historia no tenía mucho peso. ;D

**Comment by rhgarcia** [comment]
Correcto, @amorag :-) tienes razón.
Mañana montaré las tareas del sprint actual, pero en principio se abordarán Abstract, estado del arte, parte de la metodología y (sólo por mi parte) programación. 

ABSTRACT
0.- Abstract

ESTADO DEL ARTE
1.- Estado del arte
1.1.- Incluir el trabajo hecho hasta ahora

INTRODUCCIÓN
A.- Introducción 

METODOLOGÍA
2.- El monomito
3.- Análisis formal de los arquetipos y predicados base
4.- (Fusionado)
5.- Se integra en nuestro modelo EC-ABM (3 capas)
6.- Capa 1:
6.1.- Nuestros agentes eran limitados: Nuevo diseño
6.2.- Acciones que cumplan los predicados base
6.3.- Representar el autómata
6.4.- Cada transición tiene una probabilidad
7.- Capa 2:
7.1.- Interfaz de predicados base
8.- Capa 3:
8.1.- las 3 funciones fitness
8.2.- Comparación
9.- Generación de historias

EXPERIMENTAL SETUP
10.- Experimental setup
10.1.- Qué experimentos se realizarán y cómo
10.2.- Qué análisis se realziarán

RESULTADOS
11.- Resultados

CONCLUSIONES
12.- Conclusiones

**Comment by amorag** [comment]
La Intro antes del SotA. XD :P

**Comment by rhgarcia** [comment]
@amorag, cuando tienes razón, tienes razón, esto es así xD
Por cierto, @unintendedbear, tambien tienes razón. Ya cambié el nombre :-)

ABSTRACT
0.- Abstract

INTRODUCCIÓN
A.- Introducción

ESTADO DEL ARTE
1.- Estado del arte
1.1.- Incluir el trabajo hecho hasta ahora

METODOLOGÍA
2.- El monomito
3.- Análisis formal de los arquetipos y predicados base
4.- (Fusionado)
5.- Se integra en nuestro modelo EC-ABM (3 capas)
6.- Capa 1:
6.1.- Nuestros agentes eran limitados: Nuevo diseño
6.2.- Acciones que cumplan los predicados base
6.3.- Representar el autómata
6.4.- Cada transición tiene una probabilidad
7.- Capa 2:
7.1.- Interfaz de predicados base
8.- Capa 3:
8.1.- las 3 funciones fitness
8.2.- Comparación
9.- Generación de historias

EXPERIMENTAL SETUP
10.- Experimental setup
10.1.- Qué experimentos se realizarán y cómo
10.2.- Qué análisis se realziarán

RESULTADOS
11.- Resultados

CONCLUSIONES
12.- Conclusiones
13.- Trabajo futuro
