### ISSUE TITLE
Definir formalismos y metodologías para tratar con arquetipos y lenguaje natural

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#15]
Debemos cerrar las nomenclaturas, formalismos y tecnologías a usar para tratar con:
- Modelado de arquetipos. Paso a lenguaje formal
- Modelado de backstories. Paso a lenguaje natural

**Comment by rhgarcia** [comment]
Me lo asigno yo. Este Martes hablaré con Arancha San Ginés para ver si puede apoyar esta parte de algún modo. Iré volcando resultados...

**Comment by mgarenas** [comment]
Creo que yo soy aquí la menos lucha en estos ámbitos, así que dudo mucho que pueda aportar algo a la nomenclatura o a la formalidad pero sí que puedo aportar a la hora de decir que no se entiende nada o que por el contrario está todo super claro. 

Ante todo, también me gustaría que sea quien sea quien lo haga, @raiben supongo, tenga en cuenta que no debería ser muy lioso porque sino corre el riesgo de perder lucidez de los resultados posteriores que seguro que son buenísimos :-)

**Comment by rhgarcia** [comment]
Ok @mgarenas , intentaré no irme mucho por las ramas con la nomenclatura. De todos modos, como esto pasará mil revisiones, me lo iréis echando para atrás cuando algo no se entienda como deba :-)

Respecto al trabajo realizado, decir que hablé con Arancha y le entusiasmó la idea. Quedamos en que intentaría crear un modelo lógico con el monomito y me podría dar una versión en dos semanas (desde el martes pasado). La ventajas del modelo que tiene en mente es que:
- simplifica mis predicados pero mantiene una lógica similar
- los términos elegidos serán más homogéneos
- estará sustentado en una metodología de extracción de predicados a paartir de lenguaje natural
  A lo largo  del próximo sprint incorporaré el trabajo al paper.
