### ISSUE TITLE
Sprint review

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#16]
Hola a todos,

Tras revisar los comentarios, utilizaríamos una temporización que se ajuste a los puntos a tratar. Propngo la siguiente. De todas maneras, dicha tenporización debe entenderse únicamente como una guía, pues cada semana se irá revisando y podrá modificarse.
![made-timeline](https://cloud.githubusercontent.com/assets/4012515/6319701/c2e93cbe-bac6-11e4-9ee0-454786b2a0f2.jpg)
Hoy acaba el primer milestone, que nos habíamos marcado para definir el trabajo a realizar para el paper. A continuación revisaré cada aportación realizada :-)

**Comment by JJ** [comment]
Me parece bien.

**Comment by unintendedbear** [comment]
A mí también me parece bien. Ten cuidado que en mitad de la metodología se te ha colado 1 de abril en vez de 1 de marzo.
