### ISSUE TITLE
Historias de usuario

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#17]
Hola a todos,
Aquí listo algunas Historias de Usuario que he extraido. Echadle un ojo si podéis (@jj, @fergunet, @amorag, @mgarenas, @pacastillo, @unintendedbear)  para ver si en principio todas están claras :-)
Añadid las que creáis adecuadas. Mañana iré creando historias de usuario como issues y comenzaremos a asignárnoslas y a analizar el alcance (en función de la disponibilidad de cada uno).
- Escribir el abstract: basarnos en la estructura del paper para dejar claro en qué consiste el paper
- En la introducción, hablar de la importancia de la industria del videojuego para motivar la investigación en videojuegos.
- En la introducción, hablar de la importancia de la Generación de contenidos en videojuegos para motivar nuestra metodología.
- En la introducción, hablar de los ejemplos de viodejuegos procedurales de actualidad para que el/la revisor/a entienda el calado de los posibles resultados
- En la introducción, hablar de los avances de las investigaciones anteriores para poder justificar los pasos que se van dando: logros
- En la introducción, hablar de los puntos flacos de las investigaciones anteriores para poder justificar los pasos que se van dando
- En la introducción, hablar de la necesidad de formalizar los arquetipos para que la metodología tenga el rigor necesario y pueda ser aplicada.
- En la introducción, hablar de la necesidad de que el autor pueda conocer cúando un modelo de agente y mundo puedan generar cierto tipo de historias deseadas.
- En la introducción, hablar de la necesidad de que el autor pueda conocer a priori qué historias puede generar un modelo de mundo y de agente.
- En la introducción, mencionar el concepto de arquetipo y por qué interesa desde un punto de vista lúdico.
- En la introducción, mencionar el monomito y su relación con los arquetipos para que el revisor conozca cual es el eje del estudio.
- En la introducción, explicar por qué usar un modelo lógico puede ser de utilidad para modelar los arquetipos.
- En la introducción, mencionar las ventajas que ofrece la lógica en cuanto a facilidad de traducción a/desde lenguaje natural o de posibilidad de computar.
- En la introducción, mencionar la necesidad de rediseñar al agente, ya que el anterior no era capaz de ofrecer las acciones (predicados en este caso) para modelar el monomito.
- En la introducción, mencionar que los agentes responderán a los requisitos de un posible videojuego para que los revisores puedan visualizar un ejemplo de aplicación. Serán los enemigos pero se desea crear un trasfondo, que no sean planos.
- En la introducción, hacer un resumen de las secciones para que el/la revisor/a pueda conocer la estructura del escrito.
- En la introducción, mencionar que se utilizarían nuevas métricas que se pudiesen ajustar mejor al problema.
- En la metodología, explicar en qué consiste el monomito para que el/la revisor/a pueda conocer el concepto.
- En la metodología, explicar los arquetipos presentes en el monomito, para que el/la revisor/a pueda entender la necesidad de modelarlo y cómo puede apoyar al realismo de los PNCs
- En la metodología, explicar qué investigaciones, obras, etc utilizan el monomito, para que se entienda mejor la motivación del paper.
- En la metodología, explicar el proceso que permite extraer un modelo lógico a partir de lenguaje natural, para que se entienda mejor la momenclatura y evitar que el lector se pueda perder.
- En la metodología, explicar el modelo lógico que se extrae del monomito, ya que es vital para modelar tanto el agente como el fitness.
- En la metodología, explicar por qué es necesario disponer de un modelo lógico para justificar el modelo híbrido imperativo/declarativo. 
- En la metodología, explicar los predicados extraidos del monomito, sus dependencias, clasificación y relaciones, preferiblemente con imágenes, para ayudar a su lectura.
- En la metodología, explicar el modelo de 3 capas propuesto, preferiblemente acompañado de con una imagen, para que el lector sepa cómo se relacionan EC, modelo lógico y EBM.
- En la metodología, explicar que la capa 1 consiste en la implementación de agentes y mundo, para que el lector sepa ubicar dichos componentes.
- En la metodología, explicar el rediseño del agente, preferiblemente con un diagrama de estados, para que el lector entienda que hay un trabajo detrás justificado y derivado del modelo lógico.
- En la metodología, explicar la parametrización del agente para que el lector comprenda que se trata de los parámetros son un indivíduo del GA.
- En la metodología, explicar que la capa 2 consiste en los predicados base, que es la capa que permite calcular el fitness y no depende de la implementación de los agentes.
- En la metodología, explicar los predicados base localizados para que el lector comprenda que son independientes de la implementación de los agentes y el mundo.
- En la metodología, explicar mediante una tabla que requisitos debe tener el mundo (en cuanto a predicados) para poder generar cada arquetipo, de manera que el lector pueda entender que la metodología ofrece la herramienta para conocer a priori lo que se pueda alcanzar.
- En la metodología, explicar que la capa 3 define un GA que evoluciona indivíduos que parametrizan los agentes, para que quede patente la necesidad de usar algoritmos evolutivos.
- En la metodología, explicar las diferentes funciones fitness propuestas y su porqué, para que el lector entienda que un punto flaco de papers anteriores queda cubierto.
- En la metodología, explicar qué tipos de resultados pueden esperarse del experimental setup y qué tipo de conclusiones esperamos alcanzar.

**Comment by JJ** [comment]
Jolines. Venga, adelante.

**Comment by unintendedbear** [comment]
Hola,

Ya he visto que los issues de ayer ("el tsunami", para los amigos), corresponden a estas tareas. En realidad me parece bastante bien porque se van a ir cerrando rápido y nos los podemos repartir mejor.
Ahora bien, o no lo leí bien o tengo tantas cosas en la cabeza que no me acuerdo bien. ¿Cómo nos repartimos los issues? No hay nadie asignado a ninguno.

**Comment by JJ** [comment]
Cada uno que coja el que quiera, creo que dijo @raiben

El 2 de marzo de 2015, 10:34, Paloma de las Cuevas Delgado <
notifications@github.com> escribió:

> Hola,
> 
> Ya he visto que los issues de ayer ("el tsunami", para los amigos),
> corresponden a estas tareas. En realidad me parece bastante bien porque se
> van a ir cerrando rápido y nos los podemos repartir mejor.
> Ahora bien, o no lo leí bien o tengo tantas cosas en la cabeza que no me
> acuerdo bien. ¿Cómo nos repartimos los issues? No hay nadie asignado a
> ninguno.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/17#issuecomment-76681720
> .

## 

JJ

**Comment by rhgarcia** [comment]
Hola, una nota para todos:  como procedimiento general podemos decidir que ninguna tarea debe ser cerrada sin haber sido antes revisada. Para ponerla a revisión, basta con reasignarla, poner algún comentario y añadir la etiqueta "review", que he creado para tal fin.
No pasaría nada si el revisor la pasase a otro revisor cuando tenga dudas... Si alguien quiere cambiar o mejorar el procedmiento, que lo haga :-) Lo bueno de hacerlo así es que todo ha sido visto y pensado por al menos dos personas...

**Comment by rhgarcia** [comment]
Como las historias fueron pasadas a limpio, cierro el issue.
