### ISSUE TITLE
En el abstract, basarnos en la estructura definida para dejar claro en qué consiste el paper

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#18]
Proposed: En el abstract, basarnos en la estructura definida para dejar claro en qué consiste el paper

**Comment by rhgarcia** [comment]
Asignada :-)
@JJ eres el candidato idóneo para revisármela cuando acabe :-)

**Comment by JJ** [comment]
Pos qué remedio...

**Comment by rhgarcia** [comment]
Bueno, la primera versión del abstract está subida. @JJ, te he asignado la revisión. Cuando tengas un rato échale un ojo y me dices lo que he de cambiar. Gracias! :smile:

**Comment by JJ** [comment]
Te reasigno para que revises mis notas.
Realmente, título, abstract e intro deberían ir juntos, no en issues separados. Son como una cascada: título más concreto, abstract expande, intro aún más y estructura el trabajo. Pero bueno, vamos a intentarlo así.

**Comment by rhgarcia** [comment]
Ok te lo reasigno para que lo mires de nuevo y ya decidas si se cierra :-)
Hablando con los otros participantes, creemos que la mejor manera de hacer la review es ponerla directamente en el issue (aunque puedan duplicarse si se quiere en el pdf). Así en el pdf vamos minimizando el número de comentarios y va quedando más limpio, mientras que los issues van guardando toda la información. ¿Cómo lo ves?

**Comment by pacastillo** [comment]
Creo que es una buena idea. Se guarda toda la información, y en el PDF sólo se deja lo necesario. Quizás en el .tex se podría dejar un comentario con la URL al issue ???

**Comment by rhgarcia** [comment]
Perfecto, cierro issue
