### ISSUE TITLE
En la introducción, hablar de la importancia de la industria del videojuego para motivar la investigación en videojuegos.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#19]
Proposed: En la introducción, hablar de la importancia de la industria del videojuego para motivar la investigación en videojuegos.

**Comment by JJ** [comment]
1. Es una revista de videojuegos. No creo que haga falta.
2. Si lo haces, hazlo con referencias y datos actuales. No del tipo "Me han dicho que esto mola mucho"

**Comment by rhgarcia** [comment]
ok... a ver si encuentro algún estudio de la comisión europea o de algún observatorio tecnológico. En todo caso, evitaré extenderme :-)

**Comment by rhgarcia** [comment]
@amorag, quizá seas el indicado para revisar esta tarea... sobre todo si este párrafo sobra o no... por un lado, es para una revista de videojuegos, así que quizá sea redundante, pero por otro lado, puede ayudar a un futuro lector que no sepa de qué va el asunto... He puesto datos del E3 de 2014...
Te lo asigno para revisión :-) Si no puedes o no quieres, reasígnalo :-)
Cuando puedas echarle un ojo, me dices lo que debo cambiar. Gracias!

**Comment by rhgarcia** [comment]
ups, mezclé #19 y #20. Me lo reasigno...

**Comment by rhgarcia** [comment]
#19 y #20 están en el mismo párrafo. Por favor @amorag, lo dicho, si quieres y puedes revísalo y me dices si está bien, si sobra, o lo que que veas. He añadido dos referencias bibliográficas.

**Comment by JJ** [comment]
@amorag revisa esto o reasigna. Por mi parte, lo hecho en el primer párrafo está correcto así que @raiben cierra si quieres. Me apabulla tanto issue abierto.

**Comment by rhgarcia** [comment]
Gracias @JJ !!
