### ISSUE TITLE
En la introducción, hablar de la importancia de la Generación de contenidos en videojuegos para motivar nuestra metodología.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#20]
Proposed: En la introducción, hablar de la importancia de la Generación de contenidos en videojuegos para motivar nuestra metodología.

**Comment by rhgarcia** [comment]
Creo que mezclé #19 y #20...

**Comment by rhgarcia** [comment]
#19 y #20 están en el mismo párrafo. Por favor @amorag, lo dicho, si quieres y puedes revísalo y me dices si está bien, si sobra, o lo que que veas. He añadido dos referencias bibliográficas.
Gracias!

**Comment by rhgarcia** [comment]
Gracias @JJ

**Comment by amorag** [comment]
Comentarios tardíos: :_(
-  non-player characters ->  non-player characters (NPCs)
-  thousand of characters -> thousands of characters
- a procedural method to generate them is mandatory -> a procedural method to generate
  them becomes mandatory
-  could lead to a parametrization -> application leads to
- the effect of the model parameters -> the effect of some of the model parameters
- has no actions -> has not actions / has no action
- empiezas a hablar de cosas concretas del monomito (encourages, herald) antes de haberlo introducido. Pon un ejemplo más simple y conocido (héroe) o más genérico (sin entrar en detalles).
- For this reason -> nuevo párrafo
- ¿qué es el ABM layer? No la has mencionado antes y no se sabe en lo que consiste una capa
- archetypes needs -> archetypes generation/emergence requirements
- for \textit{the monomyth} in section -> ¿qué quieres decir?¿que se explica en esa sección?
- defines lo que son arquetipos después de haberlos mencionado
- On our point of view -> From our point of view
- Decir explícitamente que consideramos interesante al monomito (apoyándonos en lo mucho que se ha usado)

Echo de menos varias cosas en la intro:
- Mejor justificación del por qué del trabajo -> hablas de PCG muy poco y de las backstories poco también. Dale más bombo a lo importante que es para la inmersión y la credibilidad del mundo el que las historias sean coherentes, interesantes y cercanas a la realidad, para que el jugador se enganche y se crea el mundo.
- Separar mejor el trabajo de los anteriores. ¿Por qué es necesario este? Dices lo que se concluyó en los anteriorres, pero no sus puntos flacos. Hay que echarse un poco de mierda encima (en los anteriores) para justificar este. O decir que seguimos la línea natural del la investigación en este tema, no sé.
- Suele ponerse un resumen de lo que se va a hacer en el trabajo: el modelo a probar, cómo se va a probar, qué resultados se esperan, qué objetivo se tiene (esto hay que repetirlo mucho de muchas formas para que quede claro que es super-importante y necesario para el mundo :D).
- Comentas muy poco de que vas a usar un EA para optimizar FSMs o el modelo que vayas a seguir.
- Como te dice JJ, también falta el típico párrafo que comenta las secciones siguientes.

Espero que te sea útl. ;D

**Comment by rhgarcia** [comment]
Respecto a encourage y herald, no se me ocurren ejemplos más simples (vamos, creía que se entenderían aunque no fuesen del monomito). Se te ocurren algunos que se entiendan más? héroes es muy genérico... no podría definirlo por una acción.

**Comment by rhgarcia** [comment]
Gracias!!!
Cuando puedas le echas un ojo y me dices:
- non-player characters -> non-player characters (NPCs) -> :+1: 
- thousand of characters -> thousands of characters -> :+1: 
- a procedural method to generate them is mandatory -> a procedural method to generate them becomes mandatory -> :+1: 
- could lead to a parametrization -> application leads to -> :+1: 
- the effect of the model parameters -> the effect of some of the model parameters
  has no actions -> has not actions / has no action -> :+1: 
- empiezas a hablar de cosas concretas del monomito (encourages, herald) antes de haberlo introducido. Pon un ejemplo más simple y conocido (héroe) o más genérico (sin entrar en detalles).
  For this reason -> nuevo párrafo -> No tengo claro un ejemplo mejor. ¿Qué pondrías tu?
- ¿qué es el ABM layer? No la has mencionado antes y no se sabe en lo que consiste una capa -> Ya me ha comentado esto @Pablo. Lo reviso con sus comentarios.
- archetypes needs -> archetypes generation/emergence requirements -> :+1: 
- for \textit{the monomyth} in section -> ¿qué quieres decir?¿que se explica en esa sección? -> Quitado ya que es una referencia para alante que se usa para explicar (no para explicar la estructura del paper).
- defines lo que son arquetipos después de haberlos mencionado -> :+1:  He movido el párrafo arriba y creo que encaja bien.
- On our point of view -> From our point of view -> :+1: 
- Decir explícitamente que consideramos interesante al monomito (apoyándonos en lo mucho que se ha usado) -> :+1: Our work uses the monomyth as a frame for backstories in videogames, since it provides a basic but omnipresent set of high level behaviors that can be found in the daily life but also in the biggest adventures.

Los otros comentarios de la intro los sacaré a nuevas US para tenerlos en cuenta en el próximo sprint.

**Comment by amorag** [comment]
Todo guay. ;)

Respecto al ejemplo lo que quiero decir es que, por ejemplo, yo no sé lo que es un heraldo.
En cambio sé lo que es un héroe, o un villano.
A lo mejor es cosa mía.

He revisado el monomito y vale, el héroe y el villano implican un viaje y demás.
Pon por ejemplo el aliado, que simplemente 'acompaña' y 'ayuda' al 'héroe'.
Yo lo veo más comprensible que el heraldo. Pero insisto, puede ser cosa mía por incultura, básicamente. :_(
