### ISSUE TITLE
En la introducción, hablar de los avances de las investigaciones anteriores para poder justificar los pasos que se van dando: logros

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#22]
Proposed: En la introducción, hablar de los avances de las investigaciones anteriores para poder justificar los pasos que se van dando: logros

**Comment by JJ** [comment]
Va de suyo

**Comment by rhgarcia** [comment]
Me pongo con ello.

**Comment by fergunet** [comment]
- For this reason in the present paper we formally model ->  For this reason, in the present paper, we formally model  
- to define requirements of the ABM -> to define the requirements of the ABM 
- `In \cite{garcia2015world} we analyzed the effect of the model parameters such as the map size available food per virtual day or initial number of agents and found out that the existence of conflicts is essential for the emergence of most of our archetypes, that different archetypes need different types of conflicts and that, in many cases, conflicts are also emergent.` 

Frase muy larga, cambiarla a: 

`In \cite{garcia2015world} we analyzed the effect of the model parameters such as the map size available food per virtual day or initial number of agents. Several conclusions were attained: the existence of conflicts is essential for the emergence of most of our archetypes, different archetypes need different types of conflicts and, in many cases, conflicts are also emergent.`
- `However, this methodology for the emergence of backstories  did not use formal models to define the archetypes or the facts  of the virtual world and no {\em a priori} rules could be provided to establish whether or not a design of an agent could lead to the appearance of the archetypes.` Esta frase no me queda clara qué quieres decir. Podrías ponerla como "El principal problema de esta metodología es TAL, ya que no se usó tal cosa" (y ya enlazas guay con el párrafo de abajo)

**Comment by rhgarcia** [comment]
ok, lo reviso. Gracias!

**Comment by rhgarcia** [comment]
Terminología: Ya no estoy usando "actions" o "logs" del mundo. en su lugar, hablo de "facts" (quizá podría usar "truths"). Es un término más preciso para definir que en realidad se tratan de hechos o verdades del mundo (pueden ser acciones o no serlo ... ) y en última instancia de instanciaciones de valores de argumentos en predicados lógicos. Por ejemplo, Father(1,5) es un hecho que define que 1 es padre de 5. Me parece que llamarlo "action" es más impreciso. Qué opináis @JJ, @fergunet y @pacastillo?

**Comment by JJ** [comment]
"Events" es mejor.

El 22 de marzo de 2015, 19:32, Rubén Héctor García <notifications@github.com

> escribió:
> 
> Terminología: Ya no estoy usando "actions" o "logs" del mundo. en su
> lugar, hablo de "facts" (quizá podría usar "truths"). Es un término más
> preciso para definir que en realidad se tratan de hechos o verdades del
> mundo (pueden ser acciones o no serlo ... ) y en última instancia de
> instanciaciones de valores de argumentos en predicados lógicos. Por
> ejemplo, Father(1,5) es un hecho que define que 1 es padre de 5. Me parece
> que llamarlo "action" es más impreciso. Qué opináis @JJ
> https://github.com/JJ, @fergunet https://github.com/fergunet y
> @pacastillo https://github.com/pacastillo?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/22#issuecomment-84671723
> .

## 

JJ

**Comment by rhgarcia** [comment]
Cierto :-) :+1:

**Comment by fergunet** [comment]
- Optimally parametrizes->optimizes the parameters. No es lo mismo optimizar los parámetros que parametrizar optimamente (encontrar el óptimo)
- The analysis of the results show -> The analysis of the results shows
  - re-implementing the Agent's layer using the rules provided in this paper. -> No has mencionado las 3 capas y haces referencia a la del agente. Otra cosa, no estoy muy seguro de que "Agent's layer" esté bien, lo dejaría como "Agent Layer". De hecho, no se usan constracciones y genitivo sajón en los papers (que confirme @JJ, por si acaso)

**Comment by fergunet** [comment]
Agh, estoy gilipollas, esto era en el abstract :/

**Comment by fergunet** [comment]
Sobre la parte que tenía que revisar en este issue: 
- Después de Genetic Algorithm pon (GA) para usarlo el resto del paper
- No sé si poner "has confirmed" es muy directo.

**Comment by rhgarcia** [comment]
Hola @fergunet , puedes ver los cambios directamente en el changeset (son pocos realmente): https://github.com/geneura-papers/2015-MADE-MONOMYTH/commit/94ec1e4834f2d00d39023338375161ee39de1321
Si te parecen bien, cierra y si no, reasigna :-)
GRACIAS!
