### ISSUE TITLE
En la introducción, hablar de los puntos flacos de las investigaciones anteriores para poder justificar los pasos que se van dando

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#23]
Proposed: En la introducción, hablar de los puntos flacos de las investigaciones anteriores para poder justificar los pasos que se van dando

**Comment by JJ** [comment]
Hombre, eso siempre...

**Comment by rhgarcia** [comment]
Sorry, eran para @fergunet. Reasigno (aunque @JJ, si quieres echarle un ojo, no solo a esta sino a todas, adelante, eres el product owner)

**Comment by fergunet** [comment]
Bueno, la revisión a esta parte lo he hecho en el issue #22 Hay que dejar claro cuál era el problema de la anterior metodología, invirtiendo la frase y diciéndolo explícitamente. El principal problema es TAL, ya que se basaba en el TAL. Esto puede resolverse con TAL. (y así se enlaza guay).

**Comment by rhgarcia** [comment]
Hecho, la pongo a revisión :-)

**Comment by fergunet** [comment]
No pongas referencias a secciones futuras si no están presentadas antes, porque quien lee esto aún no sabe de qué va el asunto: quita _as we discuss on section~\ref{sec:met}_ y la de después.

El problema de esta parte es que estás mencionando los arquetipos antes de que los definas: _methodology can be used to achieve the emergence of archetypes_. Yo hablaría de los arquetipos antes.

**Comment by rhgarcia** [comment]
Ok, Entendido. La regla es: En la intro sólo mencionar otras secciones cuando se explique la estructura del paper, no para explicar conceptos.
Respecto a los arquetipos, a petición también de @amorag, los moví arriba de manera que se hable antes de ellos.
Gracias!
