### ISSUE TITLE
En la introducción, hablar de la necesidad de formalizar los arquetipos para que la metodología tenga el rigor necesario y pueda ser aplicada.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#24]
Proposed: En la introducción, hablar de la necesidad de formalizar los arquetipos para que la metodología tenga el rigor necesario y pueda ser aplicada.

**Comment by rhgarcia** [comment]
Ok... a ver cómo lo argumento :-)

**Comment by rhgarcia** [comment]
Es cercano al lenguaje natural
Tiene una sintaxis y rigor matemático
Es transformable a un programa con paradigma declarativo

**Comment by rhgarcia** [comment]
mmm... no he dicho nada de que somos los primeros que lo hacemos con el monomito.... Quedaría mejor decirlo cuando hable del monomito en la intro? o lo dejamos para luego?

**Comment by pacastillo** [comment]
Quizás más bien al final del estado del arte: Tras presentar los trabajos relacionados, etc, acabar diciendo que nosotros proponemos algo novedoso y mejor que lo presentado por los otros ya comentados.

**Comment by fergunet** [comment]
Estoy viendo que en el issue #22 he escrito demasiado xDD Cada user story es más pequeña que lo que pensaba (un párrafo).

Original:  `For this reason in the present paper we formally model the archetypes using predicate logic. A logical model allows us to describe the archetypes in a way that is  close to natural language, provides the formalism and syntax of the mathematical language and is easily transformable to a computer program in a declarative paradigm. This logical model also allows us to define requirements of the ABM layer and, following them, design a new more complex finite state automaton that better fits the archetypes needs. It is important to remark that these requirements or rules can also help to know what archetypes cannot emerge in a world inhabited by actually designed agent for a videogame.`
- For this reason in the present paper, we -> For this reason, in this paper (en lugar de present paper)
- the archetypes needs: pon directamente cuales son esas necesidades o un "such as..."
- Mete una referencia después de paradigm (que luego usarás en el SOA para justificar tu propuesta)
- by actually designed agent for a videogame. -> Esto suena raro y no sé qué quiere decir.

**Comment by rhgarcia** [comment]
Ok a los dos primeros. Respecto al cuarto, directamete lo he quitado (era redundante, ya dijimos que era un problema, dijimos que lo solventamos ahora y hasta ponímos un ejemplo).
Respecto a la referencia,  no tengo muy claro cual poner. me echas una mano @fergunet ?
Gracias!
