### ISSUE TITLE
En la introducción, hablar de la necesidad de que el autor pueda conocer cúando un modelo de agente y mundo puedan generar cierto tipo de historias deseadas.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#25]
Proposed: En la introducción, hablar de la necesidad de que el autor pueda conocer cuando un modelo de agente y mundo puedan generar cierto tipo de historias deseadas.

**Comment by rhgarcia** [comment]
Ok, ya he hablado de esto pero voy a darle más importancia...

**Comment by rhgarcia** [comment]
Añadido

**Comment by JJ** [comment]
¿En qué commit? ;-)

2015-03-21 20:40 GMT+01:00 Rubén Héctor García notifications@github.com:

> Añadido
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/25#issuecomment-84439196
> .

## 

JJ

**Comment by fergunet** [comment]
¿En qué parte está explicado esto, @raiben ?
