### ISSUE TITLE
En la introducción, hablar de la necesidad de que el autor pueda conocer a priori qué historias puede generar un modelo de mundo y de agente.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#26]
Proposed: En la introducción, hablar de la necesidad de que el autor pueda conocer a priori qué historias puede generar un modelo de mundo y de agente.

**Comment by mgarenas** [comment]
Esto no lo entiendo, podéis aclararlo más por favor.

A qué llamamos agente? qué relación tiene con un arquetipo? o es que has 
puesto agente y querías poner otra cosa?

Creo que un issue para detallar las definiciones estaría bien, aunque 
sea para nosotros, para entender a qué nos referimos cada vez y poder 
llamar a las cosas por el mismo nombre.

Maribel
On 01/03/15 19:27, Rubén Héctor García wrote:

> Proposed: En la introducción, hablararía bien.

  de la necesidad de que el autor

> pueda conocer a priori qué historias puede generar un modelo de mundo y
> de agente.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/26.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
básicamente, el estudio del monomito y su modelado lógico (lo que luego será parte de la capa 2 del modelo) permitirán definir unos predicados base. La capa 3, que es la capa de implementación debe ser capaz de generar predicados que permitan deducir los predicados base. ¿Hasta qué punto alguien puede estar seguro de que una implementación será capaz de generar el monomito o parte de sus arquetipos? ¿Bajo qué circunstancias podemos confirmar que el sistema no será capaz de encontrar ciertos arquetipos? Creo que esto podremos responderlo más o menos :-)

**Comment by rhgarcia** [comment]
Creo que con el #25 este item ya queda más o menos contestado...

**Comment by rhgarcia** [comment]
Hecho, buscar 'herald' para ver donde lo menciono y un ejemplo.
