### ISSUE TITLE
En la introducción, mencionar el concepto de arquetipo y por qué interesa desde un punto de vista lúdico.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#27]
Proposed: En la introducción, mencionar el concepto de arquetipo y por qué interesa desde un punto de vista lúdico.

**Comment by mgarenas** [comment]
¿Por qué es interesante un arquetipo desde el punto de vista lúdico?

Podríamos decir que en cualquier aspecto de la vida cotidiana existen 
los pros y contras de cualquier situación, es decir que donde alguien ve 
un vaso medio lleno, siempre hay alguien que lo ve medio vacio. Esa es 
la misión de los diferentes arquetipos, dar diferentes puntos de vista a 
una situación, por supuesto puntos de vista encontrados. Así el 
arquetipo A ante una situación S tendrá una percepción que le provoca 
una reacción AS y el arquetipo B ante la misma situación S querrá una 
reacción BS que seguramente serán reacciones diferentes si són 
arquetipos diferentes (Héroe o Villano).

Esto es tan filosófico como una discusión sobre el Bien y el Mal :-)

Maribel

On 01/03/15 19:27, Rubén Héctor García wrote:

> Proposed: En la introducción, mencionar el concepto de arquetipo y por
> qué interesa desde un punto de vista lúdico.
> 
> —
> Reply to this email directly or view i on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/27.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
Un poco sí. Habrá que ponerse un poco filosóficos :-)

**Comment by rhgarcia** [comment]
Ok, pues voy a ello
