### ISSUE TITLE
En la introducción, mencionar el monomito y su relación con los arquetipos para que el revisor conozca cual es el eje del estudio.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#28]
Proposed: En la introducción, mencionar el monomito y su relación con los arquetipos para que el revisor conozca cual es el eje del estudio.

**Comment by mgarenas** [comment]
Añade Monomito a la lista de definiciones please

maribel
On 01/03/15 19:27, Rubén Héctor García wrote:

> Proposed: En la introducción, mencionar el monomito y su relación con
> los arquetipos para que el revisor conozca cual es el eje del estudio.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/28.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
ok

**Comment by JJ** [comment]
Entiendo que esto está por hacer, ¿no?

**Comment by rhgarcia** [comment]
eso es... está en proceso :-) la dejé a mitad
