### ISSUE TITLE
Tema Articulo

### ISSUE THREAD

**Issue by mgarenas** [geneura-papers/2015-GECCO-MADE#3]
Hay ya decidido qué hacer para este artículo?

**Comment by mgarenas** [comment]
Me voy a explicar mejor. Después de leer el Readme que habéis escrito, la verdad es que me da un poco la sensación de que hemos saltado de un punto a otro, cosa que siempre se critica porque no seguimos una línea. Igual es porque no he pillado la idea con lo que hay escrito en Readme.md 

En relación al artículo de EvoStart, y por supuesto en mi opinión, lo que deberíamos de hacer es tunear un poco el algoritmo para que el número de arquetipos suban, vamos que lo que nos pasaba en casi todos los experimentos en el artículo anterior es que la emergencia de arquetipos era nula, por lo que intentaría subir ese número diseñando operadores que lo facilitaran (evidentemente no sé como) pero pensaba que ese sería el siguiente paso natural. Evidentemente, y lo repito, es mi opinión que quizás no coincida con lo que vosotros pensábais.

**Comment by JJ** [comment]
Maribel, para eso precisamente hacen falta los conflictos.
