### ISSUE TITLE
En la introducción, mencionar la necesidad de rediseñar al agente, ya que el anterior no era capaz de ofrecer las acciones (predicados en este caso) para modelar el monomito.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#30]
Proposed: En la introducción, mencionar la necesidad de rediseñar al agente, ya que el anterior no era capaz de ofrecer las acciones (predicados en este caso) para modelar el monomito.

**Comment by mgarenas** [comment]
En la lista de definiciones poner predicado y la primera definición que 
propongo es:
predicado: Acción que un agente puede tener en cuenta entre un abanico 
de posibles ante una situación S.

Aclaraciones que puede completar @raiben porque seguro que lo tiene en 
su cabeza. El conjunto de acciones está limitado a un número? nos 
interesa que esté limitado? Añadiría algo positivo al Modelo lógico que 
todos los agentes tuvieran acciones ilimitadas? o por el contrario el 
hecho de que un agente esté liminado confiere a la historia alguna 
propiedad deseada?

Maribel

On 01/03/15 19:27, Rubén Héctor García wrote:

> Proposed: En la introducción, mencionar la necesidad de rediseñar al
> agente, ya que el anterior no era capaz de ofrecer las acciones
> (predicados en este caso) para modelar el monomito.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/30.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
El conjunto de predicados no está limitado pero debe permitir deducir los predicados base, necesarios para detectar los arquetipos. A priori no se me ocurre cómo podrían los agentes tener acciones ilimitadas... Podemos dejar estas cuestiones en stand-by para posibles conclusiones, ¿te parece?

**Comment by mgarenas** [comment]
Bueno, en realidad, yo te proponía la ultima pregunta, si un agente tiene acciones limitadas, significará que sólo puede hacer algunas cosas y creo que eso le conferirá a la historia una propiedad y es la limitación de los cambios que pueden tener los agentes, vamos que un héroe no podrá nunca convertirse en villano o viceversa no? pero igual se me está yendo la cabeza  :-) . Si un agente puede hacer de todo, es decir tiene las acciones ilimitadas, podría hacer de todo y podría cambiar de arquetipo no?

**Comment by rhgarcia** [comment]
Sí, en principio, se está modelando de manera que el héroe de un viaje
puede ser el villano de otro, el mentor de otro, etc... eso da profundidad
:-)

2015-03-04 21:46 GMT+01:00 Maribel García Arenas notifications@github.com:
