### ISSUE TITLE
En la introducción, mencionar que los agentes responderán a los requisitos de un posible videojuego para que los revisores puedan visualizar un ejemplo de aplicación. Serán los enemigos pero se desea crear un trasfondo, que no sean planos.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#31]
Proposed: En la introducción, mencionar que los agentes responderán a los requisitos de un posible videojuego para que los revisores puedan visualizar un ejemplo de aplicación. Serán los enemigos pero se desea crear un trasfondo, que no sean planos.

**Comment by JJ** [comment]
Y mencionar qué requisitos podrán cumplir... por ejemplo, no pueden ser personajes interactivos. ¿o sí?
