### ISSUE TITLE
En la introducción, hacer un resumen de las secciones para que el/la revisor/a pueda conocer la estructura del escrito.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#32]
Proposed: En la introducción, hacer un resumen de las secciones para que el/la revisor/a pueda conocer la estructura del escrito.

**Comment by mgarenas** [comment]
Esto en principio se hace al final de la introducción, en el último párrafo.

Maribel

On 01/03/15 19:28, Rubén Héctor García wrote:

> Proposed: En la introducción, hacer un resumen de las secciones para que
> el/la revisor/a pueda conocer la estructura del escrito.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/32.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
Ok. Lo tenemos en cuenta :-)
