### ISSUE TITLE
En la introducción, mencionar que se utilizarían nuevas métricas que se pudiesen ajustar mejor al problema.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#33]
Proposed: En la introducción, mencionar que se utilizarían nuevas métricas que se pudiesen ajustar mejor al problema.

**Comment by pacastillo** [comment]
Más adelante hay que detallar esas métricas.
¿Tienes pensada alguna en concreto?

**Comment by rhgarcia** [comment]
Pensamos en 3... aunque habría que revisarlas. @fergunet ya redactó bastante para el paper en su versión anterior. Quizá pueda hacerte un resumencillo aquí :-)
