### ISSUE TITLE
En la metodología, explicar en qué consiste el monomito para que el/la revisor/a pueda conocer el concepto.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#34]
Proposed: En la metodología, explicar en qué consiste el monomito para que el/la revisor/a pueda conocer el concepto.

**Comment by mgarenas** [comment]
Y nosotros please :-D

Maribel
On 01/03/15 19:28, Rubén Héctor García wrote:

> Proposed: En la metodología, explicar en qué consiste el monomito para
> que el/la revisor/a pueda conocer el concepto.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/34.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
En youtube hay un vídeo maravilloso que lo explica xD
https://www.youtube.com/watch?v=yZxs_jGN7Pg
Espero que el paper sea al menos la mitad de claro a la hora de explicarlo
Quien quiera profundizar, que me pida el libro "The writer's journey" de Vogler :-)

**Comment by mgarenas** [comment]
Está chulo, gracias. Lo he tenido que ver dos veces pero creo que ya lo 
he pillado. Yo quiero ser mentor, seguro que nunca le pasa nada y es 
importante :-)

maribel
On 04/03/15 20:38, Rubén Héctor García wrote:

> En youtube hay un vídeo maravilloso que lo explica xD
> https://www.youtube.com/watch?v=yZxs_jGN7Pg
> Espero que el paper sea al menos la mitad de claro a la hora de explicarlo
> Quien quiera profundizar, que me pida el libro "The writer's journey" de
> Vogler :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/34#issuecomment-77230063.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by JJ** [comment]
Yo quiero el libro.
