### ISSUE TITLE
En la metodología, explicar los arquetipos presentes en el monomito, para que el/la revisor/a pueda entender la necesidad de modelarlo y cómo puede apoyar al realismo de los NPCs

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#35]
Proposed: En la metodología, explicar los arquetipos presentes en el monomito, para que el/la revisor/a pueda entender la necesidad de modelarlo y cómo puede apoyar al realismo de los NPCs

**Comment by mgarenas** [comment]
Ya sé que soy una pesada, pero añadir PNC, que no se escribe PNCs, a la 
lista de definiciones porque no sé lo que es y no podré aportar nada sin 
tener ni idea

Maribel
On 01/03/15 19:28, Rubén Héctor García wrote:

> Proposed: En la metodología, explicar los arquetipos presentes en el
> monomito, para que el/la revisor/a pueda entender la necesidad de
> modelarlo y cómo puede apoyar al realismo de los PNCs
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/35.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
Gracias :-)
Quería decir NPC (Non-player character)
