### ISSUE TITLE
En la metodología, explicar qué investigaciones, obras, etc utilizan el monomito, para que se entienda mejor la motivación del paper.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#36]
Proposed: En la metodología, explicar qué investigaciones, obras, etc utilizan el monomito, para que se entienda mejor la motivación del paper.

**Comment by mgarenas** [comment]
Este punto creo que casaría mucho mejor en el estado del arte.

Maribel

On 01/03/15 19:28, Rubén Héctor García wrote:

> Proposed: En la metodología, explicar qué investigaciones, obras, etc
> utilizan el monomito, para que se entienda mejor la motivación del paper.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/36.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
Sí, puede ser. Si os parece bien podemos hacer una cosa. Cuando lleguemos a esa parte pensamos si hay cosas en ña intro que queden mejor allí... y entonces las movemos.

**Comment by mgarenas** [comment]
ok

**Comment by JJ** [comment]
En la intro siempre conviene, al menos, hacer una referencia y una introducción. Luego se extiende en el estado del arte.
