### ISSUE TITLE
En la metodología, explicar el modelo lógico que se extrae del monomito, ya que es vital para modelar tanto el agente como el fitness.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#38]
Proposed: En la metodología, explicar el modelo lógico que se extrae del monomito, ya que es vital para modelar tanto el agente como el fitness.

**Comment by JJ** [comment]
Supongo que previamente habrá que explicar qué es el monomito y qué alternativas hay.
