### ISSUE TITLE
En la metodología, explicar por qué es necesario disponer de un modelo lógico para justificar el modelo híbrido imperativo/declarativo.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#39]
Proposed: En la metodología, explicar por qué es necesario disponer de un modelo lógico para justificar el modelo híbrido imperativo/declarativo.

**Comment by mgarenas** [comment]
Sí, lo habéis adivinado, añadir modelo híbrido imperativo/declarativo a 
la lista de definiciones dejando claro en qué se diferencia de un modelo 
lógico que ya debe estar añadido a la lista previamente.

Ya sé que la estructura del paper está ya decidida, pero cada vez más 
veo que una sección con un montón de definiciones no estaría nada mal.

Maribel

On 01/03/15 19:29, Rubén Héctor García wrote:

> Proposed: En la , explicar por qué es necesario disponer de
> un modelo lógico para justificar el modelo híbrido imperativo/declarativo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/39.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
Perfecto. ¿Podríamos añadirlas en una primera sección de la metodología? No se bien donde podría ir porque quizá esas definiciones se usen en la introducción... ¿Qué opináis?

**Comment by mgarenas** [comment]
Sí, yo creo que al principio de la metodología se podrían introducir todos los conceptos para que cuando empieces ha hablar de la metodología, todo el mundo tenga claro a qué se refiere cada cosa.
