### ISSUE TITLE
Cambio Nombre

### ISSUE THREAD

**Issue by mgarenas** [geneura-papers/2015-GECCO-MADE#4]
Espero que no os importe que haya cambiado el nombre para mantener un poco el criterio de papers anteriores.

Lo único que debéis hacer es volver a clonar y listo.

**Comment by mgarenas** [comment]
closed

**Comment by amorag** [comment]
Me parece mejor así. ;)

De: Maribel García Arenas [mailto:notifications@github.com] 
Enviado el: jueves, 22 de enero de 2015 12:01
Para: geneura-papers/2015-GECCO-MADE
Asunto: [2015-GECCO-MADE] Cambio Nombre (#4)

Espero que no os importe que haya cambiado el nombre para mantener un poco el criterio de papers anteriores.

Lo único que debéis hacer es volver a clonar y listo.

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2015-GECCO-MADE/issues/4 .  https://github.com/notifications/beacon/AC6-WloYHfq6SunQYIYBhotlJSivAApkks5nkM_ggaJpZM4DVuwd.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4260/8974 - Fecha de publicación: 01/22/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4260/1 - Fecha de publicación: 12/18/14
Base de datos de virus interno no está actualizado.
