### ISSUE TITLE
En la metodología, explicar los predicados extraidos del monomito, sus dependencias, clasificación y relaciones, preferiblemente con imágenes, para ayudar a su lectura.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#40]
Proposed: En la metodología, explicar los predicados extraidos del monomito, sus dependencias, clasificación y relaciones, preferiblemente con imágenes, para ayudar a su lectura.

**Comment by mgarenas** [comment]
Genial lo de las imágenes, de hecho, creo que si logro enterarme bien de 
los predicados puesto que soy la que menos controla de todo esto, podré 
intentar hacer los diagramas gráficos para torpes :-)

Maribel
On 01/03/15 19:29, Rubén Héctor García wrote:

> Proposed: En la metodología, explicar los predicados extraidos del
> monomito, sus dependencias, clasificación y relaciones, preferiblemente
> con imágenes, para ayudar a su lectura.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/40.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
Ya tengo los predicados que me ha preparado Arancha. Los tengo que pasar a limpio. Creo que quedan bastate más claros que los mios porque ha extraido el factor tiempo, entre otras cosas. Cuando lo tenga iré comentando en el ticket.
