### ISSUE TITLE
En la metodología, explicar el modelo de 3 capas propuesto, preferiblemente acompañado de con una imagen, para que el lector sepa cómo se relacionan EC, modelo lógico y ABM.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#41]
Proposed: En la metodología, explicar el modelo de 3 capas propuesto, preferiblemente acompañado de con una imagen, para que el lector sepa cómo se relacionan EC, modelo lógico y ABM.

**Comment by mgarenas** [comment]
Además de que no sé que es el EBM, siglas nuevas, y EC que para mí es 
Evolutionary Computation, pero quizás para vosotros no, yo apuntaría 
antes de explicar el modelo de tres capas, justificar por qué 
necesitamos tres capas y no dos o cuatro. Quizás vosotros lo veáis 
clarísimo, pero yo no y quizás el lector tampoco.

Maribel

On 01/03/15 19:29, Rubén Héctor García wrote:

> Proposed: En la metodología, explicar el modelo de 3 capas propuesto,
> preferiblemente acompañado de con una imagen, para que el lector sepa
> cómo se relacionan EC, modelo lógico y EBM.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/41.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
Correcto, eso es porque quería decir ABM (Agent-based Model) :-)
Me parece buena idea justificar el modelo de 3 capas. En realidad yo lo veo claro y espero poder justificarlo:
- la capa superior es la de EC. Para ella, hay una caja negra que ejecuta con unos parámetros y para evaluarla utiliza una función fitness. Utiliza las herramientas de EC para obtener la la mejor configuración de parámetros.
- La capa 2 es una capa de acoplamiento entre implementación real y modelo teórico para el fitness. Aquí ya hablamos de semántica del mundo, y predicados lógicos. Montamos los predicados base y arquetipos. Esta capa es independiente de la capa superior (que optimiza soluciones) e independiente del mundo que se ejecuta (ratas, o lo que sea).
- la capa inferior es la capa de implementación. Aquí está el ABM, y cada ejecución genera un conjunto de verdades expresadas como predicados que en última instancia permiten deducir predicados base (usados en la capa 2).
  No se si lo he explicado bien...
  Si miras el diagrama https://github.com/geneura-papers/2015-MADE-MONOMYTH/raw/master/imags/methodology_layers.pdf creo que más o menos queda reflejado lo que he dicho... :-)
