### ISSUE TITLE
En la metodología, explicar que la capa 1 consiste en la implementación de agentes y mundo, para que el lector sepa ubicar dichos componentes.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#42]
Proposed: En la metodología, explicar que la capa 1 consiste en la implementación de agentes y mundo, para que el lector sepa ubicar dichos componentes.

**Comment by JJ** [comment]
Explicar previamente qué capas hay y por qué...

**Comment by pacastillo** [comment]
Un esquema gráfico inicial será muy conveniente aquí.
El tema es complejo y más adelante ya hay planteados algunos esquemas gráficos para algunas partes, pero creo que ya a este nivel el lector debe tener una ayudica para no perderse...
