### ISSUE TITLE
En la metodología, explicar la parametrización del agente para que el lector comprenda que se trata de los parámetros son un indivíduo del GA.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#44]
Proposed: En la metodología, explicar la parametrización del agente para que el lector comprenda que se trata de los parámetros son un indivíduo del GA.

**Comment by mgarenas** [comment]
No entiendo bien lo que quieres decir pero supongo que es que hay que 
explicar los parámetros que un agente necesita y que el conjunto de esos 
parámetros para cada agente será un individuo del Algoritmo Evolutivo. 
Evidentemente el conjunto de parámetros de un agente tiene que ser 
limitado para que el individuo sea finito. Quizás esto se puede 
relacionar con la introducción cuando se habla de las acciones o 
predicados que un agente puede tener en cuenta que inicialmente hemos 
puesto finitos.

Maribel

On 01/03/15 19:30, Rubén Héctor García wrote:

> Proposed: En la metodología, explicar la parametrización del agente para
> que el lector comprenda que se trata de los parámetros son un indivíduo
> del GA.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/44.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
Eso es. Sobre todo, que sea capaz de explicar que un indivíduo en el Algoritmo Evolutivo no es un "indivíduo" del mundo... creo que es una de las cosas que más cuesta explicar.
