### ISSUE TITLE
En la metodología, explicar que la capa 2 consiste en los predicados base, que es la capa que permite calcular el fitness y no depende de la implementación de los agentes.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#45]
Proposed: En la metodología, explicar que la capa 2 consiste en los predicados base, que es la capa que permite calcular el fitness y no depende de la implementación de los agentes.

**Comment by mgarenas** [comment]
Un diagrama con las tres capas estaría genial y si logro entenderlo 
todo, puedo también intentar hacerlo.

Maribel
On 01/03/15 19:30, Rubén Héctor García wrote:

> Proposed: En la metodología, explicar que la capa 2 consiste en los
> predicados base, que es la capa que permite calcular el fitness y no
> depende de la implementación de los agentes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/45.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
Hay uno, aunque admite cambios :-)
https://github.com/geneura-papers/2015-MADE-MONOMYTH/raw/master/imags/methodology_layers.pdf

**Comment by rhgarcia** [comment]
De hecho... cambiará :-) así que toda crítica constructiva es bienvenida

**Comment by mgarenas** [comment]
jolín! pues yo me lo esperaba al revés, vamos la capa más abstracta que creo que son los agentes y el mundo arriba y conforme van bajando las capas, serían cosas más concretas, pero quizás estoy pensando en implementación del AG y se me está uniendo la implementación del AG con la capa que tú llamas implementación donde sitúas al mundo y a los agentes. 

Aún obviando lo del orden de las capas, tampoco me resulta muy claro el círculo que se forma entre World, Agent, y Predicate:Fact or primitive, esas relaciones. Por ejemplo, yo pensaba que un agente tenía una serie de acciones o predicados a ejecutar ante una determinada situación, por lo que pensaba que la relación entre agente y predicados iría en sentido contrario. Pero ... veo que me equivoco. Quizás las definiciones me ayuden a verlo de esta forma.

**Comment by rhgarcia** [comment]
Guay, de todas maneras yo lo veo así porque pienso en el sentido en que se
ejecutan en código, pero voy a intentar verlo con ojos nuevos a ver si se
me ocurre una manera más clara de mostrarlo.

2015-03-08 17:55 GMT+01:00 Maribel García Arenas notifications@github.com:
