### ISSUE TITLE
En la metodología, explicar que la capa 3 define un GA que evoluciona indivíduos que parametrizan los agentes, para que quede patente la necesidad de usar algoritmos evolutivos.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#48]
Proposed: En la metodología, explicar que la capa 3 define un GA que evoluciona indivíduos que parametrizan los agentes, para que quede patente la necesidad de usar algoritmos evolutivos.

**Comment by mgarenas** [comment]
Yo no lo enfocaría como que el AE es necesario sí o sí, sino que lo 
enfocaría como que una forma de abordar el problema es con AG, quizás en 
trabajos futuros se puede abordar desde otros puntos de vista que 
nosotros no vemos.
Pero me parece muy fuerte el hecho de que digamos que un AE es necesario 
sí o sí.

On 01/03/15 19:30, Rubén Héctor García wrote:

> Proposed: En la metodología, explicar que la capa 3 define un GA que
> evoluciona indivíduos que parametrizan los agentes, para que quede
> patente la necesidad de usar algoritmos evolutivos.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/48.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
Tienes razón. Lo tenemos en cuenta :+1:

**Comment by JJ** [comment]
Al final es un método de optimización entre otros muchos... Quizás sea mejor usar alguno más ligero como Simulated Annealing o un hillclimbing.

**Comment by pacastillo** [comment]
Quizás para un trabajo posterior (o mismamente para la tesis) se podría plantear ver cómo funcionan esos métodos de optimización, y compararlos, claro.
