### ISSUE TITLE
En la metodología, explicar las diferentes funciones fitness propuestas y su porqué, para que el lector entienda que un punto flaco de papers anteriores queda cubierto.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#49]
Proposed: En la metodología, explicar las diferentes funciones fitness propuestas y su porqué, para que el lector entienda que un punto flaco de papers anteriores queda cubierto.

**Comment by mgarenas** [comment]
La metodología debería ir segmentada en subsecciones, y una de ellas 
debería estar dedicada sólo y exclusivamente a la función de fitness, 
explicando muy pero que muy bien que las funciones de fitness marcan 
toda la evolución.

Maribel
On 01/03/15 19:30, Rubén Héctor García wrote:

> Proposed: En la metodología, explicar las diferentes funciones fitness
> propuestas y su porqué, para que el lector entienda que un punto flaco
> de papers anteriores queda cubierto.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/49.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by rhgarcia** [comment]
Ok, me parece correcto. ¿Entonces la definción del mundo también sería una subsección o directamente una sección aparte?

**Comment by mgarenas** [comment]
Pues si se queda muy larga, una sección aparte y si no, una subsección sería suficiente supongo.
