### ISSUE TITLE
Revise introduction to incorporate the focus of the article

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015-GECCO-MADE#5]
And expand abstract accordingly. Examine all archetypes and characterize 
1. Which conflicts are there
2. Which ones can really be incorporated into our framework.

**Comment by rhgarcia** [comment]
First draft of the introduction. I still have to add a brief review of the specific conflicts but I may have a better vision of them after the SOA...
Please, take a look @JJ, @fergunet and @amorag and check if everything in as understandable as possible

**Comment by amorag** [comment]
First revision done, @raiben. ;D

**Comment by JJ** [comment]
@raiben please check everything @amorag has included into the article and and rest of the issues, especially #3 and #6 for the focus of the article. We should probably decide one of them today.

**Comment by rhgarcia** [comment]
Ok, to sum up...

Currently, In the introduction I have mentioned two factors of the fitness that need to be explored:
- How the archetypes are retrieved (in this context the paper will study more conflict-based archetypes) 
- How to calculate a fitness of the world by measuring the number of archetypes present in the agent that inhabit it (in this context different alternatives for the calculus of the world fitness will be provided).

For both of them I would try to propose different approaches but the may change depending on the SOA and the methodology (still undone)... Anyway, I can explicitly introduce the two goals pointed by @JJ:
1. Design a fitness function that is well explained and motivated.
2. Do an experimental design that checks evolutionary algorithm parameters for the fitness (or different fitnesses) we design

But, in issue #6, @amorag says that we may not change the fitness and the operators at the same time, and he proposes to change the operators. @mgarenas also says that she would focus the paper in changing the EA parameters.
The problem with changing the EA parameters is that, IMHO, the archetypes used for the Evostar are still a bit primitive and I personally think that more archetypes would enrich the research (at least a good analysis based in the conflicts)...
...So, please tell me what you all think. Anyway, I can add this issue (the one related to the EA parameters) to the introduction and in the future we can cut off the goals of the paper.

**Comment by fergunet** [comment]
I also support the fitness thing, rather than "another paper about parameter tuning". It is more interesting to continue the research in, well, story generation, and therefore, to work in the fitness definition, conflicts, and content creation than launch the same EA again and again.

**Comment by JJ** [comment]
Finally, he's going to explain better the fitness and maybe try a different
one. There's no time for much more.

**Comment by mgarenas** [comment]
Ok

Enviado de Samsung Mobile

<div>-------- Mensaje original --------</div><div>De: Juan Julián Merelo Guervós notifications@github.com </div><div>Fecha:26/01/2015  21:50  (GMT+01:00) </div><div>Para: geneura-papers/2015-GECCO-MADE 2015-GECCO-MADE@noreply.github.com </div><div>Cc: Maribel García Arenas mgarenas@ugr.es </div><div>Asunto: Re: [2015-GECCO-MADE] Revise introduction to incorporate the focus of
  the article (#5) </div><div>
</div>Finally, he's going to explain better the fitness and maybe try a different
one. There's no time for much more.

**Comment by mgarenas** [comment]
Ok

Enviado de Samsung Mobile

<div>-------- Mensaje original --------</div><div>De: Pablo García Sánchez notifications@github.com </div><div>Fecha:26/01/2015  21:10  (GMT+01:00) </div><div>Para: geneura-papers/2015-GECCO-MADE 2015-GECCO-MADE@noreply.github.com </div><div>Cc: Maribel García Arenas mgarenas@ugr.es </div><div>Asunto: Re: [2015-GECCO-MADE] Revise introduction to incorporate the focus of
  the article (#5) </div><div>
</div>I also support the fitness thing, rather than "another paper about parameter tuning". It is more interesting to continue the research in, well, story generation, and therefore, to work in the fitness definition, conflicts, and content creation than launch the same EA again and again.

**Comment by amorag** [comment]
I think that the paper, as the title points out must deal with 'how to promote conflicts to enrich the generated archetypes'.

Thus, this can be done in two main ways (in my opinion):
1) Adapting/Changing the fitness function to increase the obtained value when there are more conflicts.
2) Adapting the genetic operators (not the parameters), namely the crossover and mutation, to generate 'nemesis' agents.

To this aim, we must really emphasize in the text (and definitely demonstrate) that the main assumption is true, i.e. prove that the arising of conflicts is very positive to reach the goals of MADE (obtaining realistic and reliable background stories).

So, if you agree with this objective, this should be in our minds whenever we write something in the paper. This is a lack that I have detected in most of our works (including mines), we don't focus in the selling point everywhere in the text. ;)

**Comment by JJ** [comment]
If this is no longer current, it should be closed... if it is current, we should work on it and check if it corresponds to the new focus!

**Comment by JJ** [comment]
Is this still current? Does anybody care about closing or doing something about it? Somebody? Anybody?
