### ISSUE TITLE
En la metodología, explicar qué tipos de resultados pueden esperarse del experimental setup y qué tipo de conclusiones esperamos alcanzar.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#50]
Proposed: En la metodología, explicar qué tipos de resultados pueden esperarse del experimental setup y qué tipo de conclusiones esperamos alcanzar.

**Comment by pacastillo** [comment]
Efectivamente, en la metodología podemos centrarnos en los experimentos a realizar y qué tipos de análisis se harán. Y una sección aparte, centrarla en el modelo.

**Comment by rhgarcia** [comment]
Genial. En realidad yo concebía este issue como algo pequeño que fuese ampliado en el experimental setup... ¿Os parace bien?
En todo caso, dejaría esa profundización del tema de los experimentos para el grooming del próximo sprint. Ahí vuestra ayuda va a ser vital, creo :-)
