### ISSUE TITLE
En la introducción, mencionar las ventajas que ofrece la lógica en cuanto a facilidad de traducción a/desde lenguaje natural o de posibilidad de computar.

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#51]
Proposed: En la introducción, mencionar las ventajas que ofrece la lógica en cuanto a facilidad de traducción a/desde lenguaje natural o de posibilidad de computar.

**Comment by amorag** [comment]
Rubén, está bien que seas muy metódico, pero ¿no son estos demasiados Issues? XD

De: Rubén Héctor García [mailto:notifications@github.com] 
Enviado el: domingo, 1 de marzo de 2015 19:40
Para: geneura-papers/2015-MADE-MONOMYTH
Asunto: [2015-MADE-MONOMYTH] En la introducción, mencionar las ventajas que ofrece la lógica en cuanto a facilidad de traducción a/desde lenguaje natural o de posibilidad de computar. (#51)

Proposed: En la introducción, mencionar las ventajas que ofrece la lógica en cuanto a facilidad de traducción a/desde lenguaje natural o de posibilidad de computar.

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2015-MADE-MONOMYTH/issues/51 .  https://github.com/notifications/beacon/AC6-WrRYj-RhawHo7KWwgoVXhTPf6AFXks5nw1RmgaJpZM4Dnuvy.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4299/9206 - Fecha de publicación: 03/01/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4299/9185 - Fecha de publicación: 02/26/15

**Comment by rhgarcia** [comment]
Bueno, estamos en las primeras fases de la metodología, ya iremos perfilándolo. Y bueno... si son historias pequeñas se pueden ir cerrando antes :-)
