### ISSUE TITLE
Hacer algo con `made_old_paper`

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015-GECCO-MADE#53]
La ciencia es como el cocido: se aprovecha todo. Si se va a usar una estructura nueva, se puede aprovechar la antigua, aunque sea sólo por la cantidad de trabajo de @fergunet @amorag y cía. Responder a las preguntas que hay, aclararlo y publicarlo como informe técnico en @figshare, por ejemplo. 
Aparte, faltan 4 referencias. Al menos habría que añadirlas a la blblio.

**Comment by JJ** [comment]
Subo la prioridad a ver si le hacéis caso...

**Comment by rhgarcia** [comment]
estoy reutilizando material. No haría nada con el old paper hasta acabar
este porque mucho se va a reutilizar.

**Comment by JJ** [comment]
Yo más bien diría al revés. Vamos a hacer lo que podamos para no reutilizar
ese material, sino dejarlo ya publicado y citarlo.
