### ISSUE TITLE
Objetivos del paper y metodología

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#54]
Hola a todos, 
Antes de seguir, para que todo el mundo tenga claro los objetivos del paper, los listo a continuación. Por favor, si alguien no los ve, no está de acuerdo o quiere ampliarlos o reducirlos, este es el momento de hablarlo :-)  @JJ, @fergunet, @amorag, @pacastillo, @mgarenas, @unintendedbear .
- El monomito es un conjunto de arquetipos literarios (héroe, shadow, etc) que refleja lo que comunmente se llama el patrón del viaje del héroe, aplicado a infinidad de películas, libros, guiones, juegos, etc etc etc
- Se va a realizar un modelo lógico del monomito
- Ese modelo lógico será expresado en lógica de predicados. Los arquetipos incluidos.
- En base a esos predicados, se modelará una máquina de estados finitos común a todos los agentes, que sea capaz de producir esos predicados, o predicados más simples que permitan deducir esos predicados.La máquina se parametrizará con valores de probabilidades que permiten pasar de un estado a otro.
- La máquina que modelamos ahora puede cambiar de un juego a otro, pero seremos capaces de definir unos criterios para crearla y que pueda surgir el monomito.
- Esas probailidades se codificarán como un cromosoma.
- Dicho cromosoma será optimizado mediante un algoritmo genético.
- Se alorará la posibilidad de tener diferentes grupos de paŕametros, de manera que unos agentes se parametricen con el grupo 1, otros con el 2, etc. De este modo, podremos simular personalidades. Todos los agentes comparten máquina de estados pro diferentes agentes podrán tener diferentes probabilidades.
- Una simulación consistirá en lanzar "muchos" agentes con la misma o diferenets personalidades que interactuen entre sí. Esos agentes produciran "verdades" del mundo, que estarán expresadas como predicados.
- Cada simulación será evaluada con un fitness. Ese fitness medirá la aparición de arquetipos mediante el uso de lógica de predicados.
- Un GA optimizará el cromosoma, es decir (personalidad/es de los agentes) de manera que maximice el fitness.
- El fitness de dicho GA va a estar definido por los arquetipos, es decir, arquetipos que se deducirán de las verdades del mundo. 
- Se utilizarán 3 métricas para seleccionar el mejor fitness
- Se mostrará un ejemplo de historia generada (automatizada) en narrativa e idioma inglés. 

Innovaciones de este paper:
- No conocemos a nadie que haya definido formalmente el monomito
- Ofrece un método para crear FSM compatibles con el monomito y permitir conocer a priori qué arquetipos no podrán emerger en una FSM creada.

**Comment by JJ** [comment]
OK. Pero no te empantanes con la definición formal del monomito, no es el
objetivo principal de la tesis. Eso, de por sí, puede ser una tesis o dos,
pero de filosofía o de literatura.
El objetivo del paper tampoco es utilizar tres métricas. Es usar una cantidad aceptable de métricas para seleccionar el fitness.

**Comment by pacastillo** [comment]
¡¡¡triple doctorado!!!

**Comment by JJ** [comment]
:-)

**Comment by rhgarcia** [comment]
Hola, esa parte ya ha sido hecha :-) es más o menos como la hice yo ara el
GECCO, pero mejor y más simple xD

**Comment by amorag** [comment]
Yo añadiría:
- Cuántos parámetros se van a utilizar (se van a optimizar).
- La simulación, si no me equivoco, consiste en que esos personajes interactúen durante varios días (o generaciones, o como se quiera llamar). ;)
- El fitness no está claro qué pretende maximizar o minimizar. Lo que yo recuerdo es que no se trata de que aparezcan el mayor número posible de un tipo o de varios, sino un número que se ajuste a un porcentaje que nosotros definimos. Aunque eso iba a cambiarse en este artículo, ¿no? 
  Queríais usar varias funciones de fitness, fomentando la aparición de conflictos, ¿es así?.

**Comment by rhgarcia** [comment]
Hola,
Gracias por las puntualizaciones,
- Respecto al primer punto, aun no lo se, pero puede que sean varias
  decenas... aun está por modelar y dependen directamente del diagrama de
  estados. Tu dijiste que un número elevado no es problema porque así se
  justifica el uso de un GA, ¿no?
- Respecto al punto 2, correcto. Hemos de evitar el uso de generaciones en
  este contexto para evitar malentendidos. Yo uso el término tiempo virtual
  (días virtuales en el caso de las ratas, minutos virtuales en el caso de
  los nuevos personajes por modelar), lo añadiré al listado.
- Respecto al punto 3, hay 3 criterios: mayor número de arquetipos, mayor
  número de arquetipos diferentes y mayor número de arquetipos diferentes y
  con mayor repartición entre los personajes. Los añadiré al listado.

De los que no han respondido, alguien tiene alguna duda?
Por otro lado, echadle un ojo por favor a las US actuales para ver si las
motivaciones y los puntos están bien. Si sobran, si faltan, etc. Si hay
dudas, preguntadlas.

Gracias!

**Comment by amorag** [comment]
Bueno, varias decenas quiza sean muchos. XD

Me refería a que es más defendible usar un AG para optimizar 15 parámetros que 5, pero claro, a mayor número de parámetros más difícil será optimizarlos todos (más generaciones serán necesarias). ;)
Aunque que eso no te condicione. Tú 'extrae' todos los que hagan falta y luego se estudian y se reducen si es posible (algunos podrían ser función de otros).
