### ISSUE TITLE
Usar "we" en el texto o no?

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-GECCO-MADE#55]
Algunas revisiones han aceptado que se use el "we" en el texto (yo mismo, por ejemplo en el issue #22 no me he quejado), pero todavía no tengo claro si se debe usar o no en artículos científicos. Me ha dicho @raiben que todas estas movidas deben discutirse por issues, no por hangouts ni otros medios.

Bueno, ¿qué hacemos con el "we" en este paper?

**Comment by JJ** [comment]
Se usa sí y sólo sí se quiere hacer énfasis en algo que se ha aportado o ha
hecho. No en el resto de los casos.

**Comment by mgarenas** [comment]
Yo abogo siempre por no usar el we. Lo veo mas formal y menos de coleguita. Pero se que todos tendemos a usar we a menudo porque nos sale mas naturalmente. Incluída yo. En cualquier caso tiene que ser todo con el mismo estilo.

Maribel

Enviado de Samsung Mobile

<div>-------- Mensaje original --------</div><div>De: Pablo García Sánchez notifications@github.com </div><div>Fecha:25/03/2015  13:00  (GMT+01:00) </div><div>Para: geneura-papers/2015-MADE-MONOMYTH 2015-MADE-MONOMYTH@noreply.github.com </div><div>Cc:  </div><div>Asunto: [2015-MADE-MONOMYTH] Usar "we" en el texto o no? (#55) </div><div>
</div>Algunas revisiones han aceptado que se use el "we" en el texto (yo mismo, por ejemplo en el issue #22 no me he quejado), pero todavía no tengo claro si se debe usar o no en artículos científicos. Me ha dicho @raiben que todas estas movidas deben discutirse por issues, no por hangouts ni otros medios.

Bueno, ¿qué hacemos con el "we" en este paper?
