### ISSUE TITLE
Fitness: is that the only one possible?

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015-GECCO-MADE#7]
Fitness is quite important and is an essential part of the work. Just a bit of space is devoted to it. A whole section should be devoted, and
1. Explain it _much_ better. Do you look for archetypes in the whole history? In the last generation? What's actually the _rate_?
2. Why the logs? Makes no sense at all.
3. Shouldn't you be looking at _entropy_? When there are several archetypes, wouldn't you want them to be as _informational_ as possible?
4. Why maximizing the _number_ or _rate_? Why not maximize the number of days they exist or how early in the _story_ they appear? Shouldn't we be looking at different fitnesses?

The problem with comparing fitnesses is, well, how to compare them. Shouldn't we have an independent measure of this?

**Comment by fergunet** [comment]
I think we should first clarify the things we want to measure in the world to ensure the fitness function we are modeling is a good way to measure a good story. By now we are considering the next things:
- The number of archetypes is measured during all the execution of the world (the story)
- The more archetypes the better
- The more _different_ archetypes the better (that is, I prefer 1 hero and 1 villain than 2 villains). This is why the log usage, to avoid a linear fitness, but as @JJ says the entropy (a way to measuring the difference) thing would be a better measure than our "log" thing.

Also, we are measuring the number archetypes (that depend upon conflicts). Maybe we should measure the "conflicts" directly instead the archetypes (I know it is almost the same thing, but we can focus on that, and not count the number of rats, but the number of conflicts, establishing in this paper _what_ a conflict is, based in pre-conditions and post-conditions).

So, maybe in this paper we should focus in improving the fitness function, in a way that it actually measures the interest of a story, taking into account:
- coherence: still, we are saying "coherent backstories" in our paper and not measuring this. Maybe set a number of restrictions (a hero cannot hurt innocent people)
- amount: the more number of archetypes/conflicts the better
- variety (difference/entropy): the more different archetypes/conflicts the better
- any other thing?

Thoughts @raiben ?

**Comment by rhgarcia** [comment]
Ok, I'll have to read it more carefully, but it seems well. Only two
annotations:
- coherence, as defined by @fergunet, has never been measured, but
  coherence, defined as the lack of cause-consequence inconsistencies (time,
  localisation, relationships, etc) is inherent to the bottom up world
  creation. That's why I always say that this approach is coherent.
- just to clarify, the logs are the output of the world and the mechanism
  to evaluate the archetypes. Without logs, we would need other data
  structure to detect the presence of an archetype in an agent.

**Comment by rhgarcia** [comment]
Ok, I have read again the questions and comments, and I think that I that
can prepare a draft (between today and tomorrow) that explains those
concepts and propose a fitness calculation that takes into account the
different but logical approaches from @JJ and @fergunet. Thanks xDD

**Comment by JJ** [comment]
Great, @raiben

**Comment by amorag** [comment]
My two cents here.

First, I think that this paper should be focused on a fitness study. The current fitness function must be better described and justified, as @JJ said.

Again, I'll take into account Evo\* reviewers' comments in this respect.
One of them said:

"Moreover, the fitness function is not very well motivated, why is it better to have two archetypes with rates of 0.25 than to have one with a rate of 0.5? If there is only one with rate of 0.5, what archetypes do the other agents have? I think this could be explained better..."

In addition, if the conclusions previously reached point to conflicts as the main factor for getting a, let's say, 'good behaviour' of the generated world, I'll propose here some approaches of getting more conflicts in the evolution of the world, mainly by means of the fitness function, but this could be also promoted changing any of the evolutionary operators, such as the crossover or mutation ones, to generate 'nemesis' agents.

Thus, the paper should focus on some different approaches of promoting conflicts in the algorithm, and the influence (analysis of obtained results) of any of them.

**Comment by JJ** [comment]
I think that from this we have to
1. Design a fitness function that is well explained and motivated.
2. Do an experimental design that checks evolutionary algorithm parameters for the fitness (or different fitnesses) we design. Please, @raiben , can you come up with several alternatives? @fergunet ?

**Comment by JJ** [comment]
You could tale a look at this paper http://icec2014.info/proceedings/papers/11_icec2014.pdf 
I think that at the end of the day what we need are interesting stories. Different fitness functions could be compared in their capability to generate interesting stories, and this paper could help us to measure "interestingness"
