### ISSUE TITLE
Archetypes analysis

### ISSUE THREAD

**Issue by rhgarcia** [geneura-papers/2015-GECCO-MADE#9]
Mi idea es ser capaz de definir unos predicados que llamo "Base" o "Primitivas", que deben ser implementados por el mundo virtual, y unos predicados derivados que definirán los arquetipos y que no dependen del mundo. Espero ser capaz de clasificar los mundos virtuales en función de las primitivas que ofrecen, y por lo tanto, de los arquetipos que, en teoría, podrían emerger.

Por ejemplo, analizando los arquetipos más típicos (la famosa referencia a The hero's Journey), he sido capaz de extraer hasta 11 predicados "base" que puede tener el mundo: Conflict(c,h,s), ConflictTime(c,t), Before(t1,t2), JustBefore(t1,t2), Wins(c,w), Bad(c,s), Guides (m,h,s,t1,t2), Encourages (hd,h,s,t1,t2), Helps (a,h,t1,t2), Acompanies (tr,h,t1,t2) y Tricks(tr,t1,t2). (se explican más abajo pero aun tiene que explicarse mucho mejor, esto son solo unas notas).
Si el mundo puede implementar los 6 primeros, ya es capaz de devolver 3 arquetipos. si los implementa todos, podrá devolver los 8 arquetipos. La gracia es que unos predicados dependen de otros, pero todos en esencia dependen de dos predicados base "Conflict" y "Bad", es decir... lo que se considera malo y lo que se considera un conflicto entre dos agentes o elementos (nuestra tesis). Sería bonito incluso representar los predicados en un arbol indicando sus dependencias... los nodos base serían Confict, Bad y algunos predicados (helpers) que ayudan a trabajar con medidas temporales. A partir de ahí vendría un arbol muy simpático. 

Podría hacer lo que he hecho con Hero's Journey, pero con Romeo y Julieta: son 12 tropos según tvtropes. Intuyo que tendría que añadir unas primitivas más para expresar relaciones de parentesco y amor. De nuevo, el conflicto estara constántemente apareciendo. 

Ah, he expresado los predicados de manera muy sencilla, pero no sería complicado pasarlo a un lenguaje lógico como prolog, volcar los logs como predicados y luego implementar las primitivas... de hecho, me llama mucho la atención pero no va a dar tiempo ahora mismo :-(

Bueno, dejo esto aquí para seguir mañana. Si queréis echarle un ojo @fergunet y @JJ admito críticas no destructivas :-)
## Mis notas:

Según Vogler, existen los arquetipos:
- héroe
- Shadow: Villano, enemigo, el enemigo interior, represiones.
- Mentor: Guía o principios
- Heraldo: Persona o evento que llama a la aventura
- Threshold guardian: obtáculos para la consecución del objetivo, ya sean personajes o emociones
- Shapeshifter: Cambios reales o percibidos.
- Trickster: Personajes o elementos que acompañan al héroe. Amigos, personajes que promueven el cambio.
- Aliados: 

// Base
// Conflict(c,h,s): Hay un conflicto c entre h y s
// ConflictTime(c,t): El conflicto c ocurre en el instante t
// Before(t1,t2): t1 es un momento anterior a t2
// JustBefore(t1,t2): t1 es un momento inmediatamente anterior a t2
// Wins(c,w): w ha ganado el conflicto
// Bad(c,s): s tiene una alineación mala antes de que se produzca el conflicto c
//
// Derivados:
// Jorney(j, c1, c2): j es una aventura que comienza con el conflicto c1 y acaba
// con el conflicto c2 
// Hero(h, j): h es un/a héroe/heroina de una aventura j
// Shadow(s,j): s es shadow de h en la aventura j

Conflict(c1,h,s) AND ConflictTime(c1,t1) AND Wins(c1,s) AND Bad(c1,s)
 AND Conflict(c2,h,s) AND ConflictTime(c2,t2) AND Wins(c2,h) AND Bad(c2, s)
 AND Before (t1,t2) -> Journey (j,c1,c2) AND Hero(h, j) AND Shadow (s, j)

// Derivado:
// ThresholdGuardian(tg,j): tg es un obstáculo en la aventura j 

Journey(j,c1,c2) AND AND ConflictTime(c1,t1) AND ConflictTime (c2, t2)
 AND Conflict(tg,h,s) AND ConflictTime(c,t3)
 AND !Shadow(tg,j)
 AND Before(t1,t3) AND Before(t3,t2) -> ThresholdGuardian(tg,j)

// Base:
// Guides (m,h,s,t1,t2): m guía a h para vencer a s entre t1 y t2
//
// Derivados:
// Mentor (m, j): m es mentor de h desde el conflicto 1 al conflicto 2 

Journey(j, c1, c2) AND ConflictTime(c1,t1) AND ConflictTime(c2,t2)
 AND Hero(h,j) AND Shadow(s,j) AND Guides(m,h,s,t1,t2) -> Mentor(m,j)

// Base:
// Encourages (hd,h,s,t1,t2); hd anima a h contra s entre un tiempo t1 y un tiempo t2
//
// Derivado:
// Herald(hd,j): hd es un heraldo para el heroe h para su aventura j

Journey (j,c1,c2) AND Hero(h,j) AND Shadow(s,j) AND Encourages(hd,h,s,t1,t2) 
 AND ConflictTime(c1,t1) AND ConflictTime (c2, t2)-> Herald (hd,j) 

// Base:
// Helps (a,h,t1,t2): a ayuda a h entre los momentos t1 y t2
//
// Derivado:
// Allied(a,j): a es un aliado del héroe en la aventura j

Journey(j,c1,c2) AND Hero(h,j) AND Helps(a, h, t1, t2) 
 AND ConflictTime(c1,t1) AND ConflictTime (c2, t2) -> Allied (a, j)

// Base:
// Acompanies (sh,h,t1,t2): acompaña al heroe e en entre los momentos t1 y t2
// Tricks(sh,t1,t2); Actua como trickster (será complejo de definir y dependerá del mundo)
//
// Derivado:
// Allied(a,j): a es un aliado del héroe en la aventura j

Journey(j,c1,c2) AND Hero(h,j) AND Acompanies(tr, h, t1, t2)
 AND Tricks(tr,t1,t2) 
 AND ConflictTime(c1,t1) AND ConflictTime (c2, t2) -> Trickster (tr, j)

// Derivado:

(Mentor(c,j) AND Herald(c,j))
 OR (Mentor(c,j) AND ThresholdGuardian(c,j))
 OR (Mentor(c,j) AND Herald(c,j))
 OR (Mentor(c,j) AND Allied(c,j))
 OR (Mentor(c,j) AND Trickster(c,j))
 OR (Herald(c,j) AND ThresholdGuardian(c,j))
 OR (Herald(c,j) AND Herald(c,j))
 OR (Herald(c,j) AND Allied(c,j))
 OR (Herald(c,j) AND Trickster(c,j))
 OR (ThresholdGuardian(c,j) AND Herald(c,j))
 OR (ThresholdGuardian(c,j) AND Allied(c,j))
 OR (ThresholdGuardian(c,j) AND Trickster(c,j))
 OR (Herald(c,j) AND Allied(c,j))
 OR (Herald(c,j) AND Trickster(c,j))
 OR (Allied(c,j) AND Trickster(c,j)) -> Shapeshifter(c,j)

**Comment by JJ** [comment]
Te estás liando un poco con la terminología. Estás usando letritas para
indicar el tipo de arquetipo, cuando deberías usarlas para expresar
restricciones. Las letritas deberían indicar básicamente dos cosas: o
individuo o tiempo. No sé si conflicto también, pero un conflicto sería un
evento, así que, por ejemplo, conflict(c,h,s) debería ser c=conflict(a_1,
a_2) y definirse de alguna forma ¿no?

El 29 de enero de 2015, 2:24, Rubén Héctor notifications@github.com
escribió:

> Mi idea es ser capaz de definir unos predicados que llamo "Base" o
> "Primitivas", que deben ser implementados por el mundo virtual, y unos
> predicados derivados que definirán los arquetipos y que no dependen del
> mundo. Espero ser capaz de clasificar los mundos virtuales en función de
> las primitivas que ofrecen, y por lo tanto, de los arquetipos que, en
> teoría, podrían emerger.
> 
> Por ejemplo, analizando los arquetipos más típicos (la famosa referencia a
> The hero's Journey), he sido capaz de extraer hasta 11 predicados "base"
> que puede tener el mundo: Conflict(c,h,s), ConflictTime(c,t),
> Before(t1,t2), JustBefore(t1,t2), Wins(c,w), Bad(c,s), Guides
> (m,h,s,t1,t2), Encourages (hd,h,s,t1,t2), Helps (a,h,t1,t2), Acompanies
> (tr,h,t1,t2) y Tricks(tr,t1,t2). (se explican más abajo pero aun tiene que
> explicarse mucho mejor, esto son solo unas notas).
> Si el mundo puede implementar los 6 primeros, ya es capaz de devolver 3
> arquetipos. si los implementa todos, podrá devolver los 8 arquetipos. La
> gracia es que unos predicados dependen de otros, pero todos en esencia
> dependen de dos predicados base "Conflict" y "Bad", es decir... lo que se
> considera malo y lo que se considera un conflicto entre dos agentes o
> elementos (nuestra tesis). Sería bonito incluso representar los predicados
> en un arbol indicando sus dependencias... los nodos base serían Confict,
> Bad y algunos predicados (helpers) que ayudan a trabajar con medidas
> temporales. A partir de ahí vendría un arbol muy simpático.
> 
> Podría hacer lo que he hecho con Hero's Journey, pero con Romeo y Julieta:
> son 12 tropos según tvtropes. Intuyo que tendría que añadir unas primitivas
> más para expresar relaciones de parentesco y amor. De nuevo, el conflicto
> estara constántemente apareciendo.
> 
> Ah, he expresado los predicados de manera muy sencilla, pero no sería
> complicado pasarlo a un lenguaje lógico como prolog, volcar los logs como
> predicados y luego implementar las primitivas... de hecho, me llama mucho
> la atención pero no va a dar tiempo ahora mismo :-(
> 
> Bueno, dejo esto aquí para seguir mañana. Si queréis echarle un ojo
> @fergunet https://github.com/fergunet y @JJ https://github.com/JJ
> admito críticas no destructivas :-)
> Mis notas:
> 
> Según Vogler, existen los arquetipos:
> - héroe
> - Shadow: Villano, enemigo, el enemigo interior, represiones.
> - Mentor: Guía o principios
> - Heraldo: Persona o evento que llama a la aventura
> - Threshold guardian: obtáculos para la consecución del objetivo, ya
>   sean personajes o emociones
> - Shapeshifter: Cambios reales o percibidos.
> - Trickster: Personajes o elementos que acompañan al héroe. Amigos,
>   personajes que promueven el cambio.
> - Aliados:
> 
> // Base
> // Conflict(c,h,s): Hay un conflicto c entre h y s
> // ConflictTime(c,t): El conflicto c ocurre en el instante t
> // Before(t1,t2): t1 es un momento anterior a t2
> // JustBefore(t1,t2): t1 es un momento inmediatamente anterior a t2
> // Wins(c,w): w ha ganado el conflicto
> // Bad(c,s): s tiene una alineación mala antes de que se produzca el
> conflicto c
> //
> // Derivados:
> // Jorney(j, c1, c2): j es una aventura que comienza con el conflicto c1 y
> acaba
> // con el conflicto c2
> // Hero(h, j): h es un/a héroe/heroina de una aventura j
> // Shadow(s,j): s es shadow de h en la aventura j
> 
> Conflict(c1,h,s) AND ConflictTime(c1,t1) AND Wins(c1,s) AND Bad(c1,s)
> AND Conflict(c2,h,s) AND ConflictTime(c2,t2) AND Wins(c2,h) AND Bad(c2, s)
> AND Before (t1,t2) -> Journey (j,c1,c2) AND Hero(h, j) AND Shadow (s, j)
> 
> // Derivado:
> // ThresholdGuardian(tg,j): tg es un obstáculo en la aventura j
> 
> Journey(j,c1,c2) AND AND ConflictTime(c1,t1) AND ConflictTime (c2, t2)
> AND Conflict(tg,h,s) AND ConflictTime(c,t3)
> AND !Shadow(tg,j)
> AND Before(t1,t3) AND Before(t3,t2) -> ThresholdGuardian(tg,j)
> 
> // Base:
> // Guides (m,h,s,t1,t2): m guía a h para vencer a s entre t1 y t2
> //
> // Derivados:
> // Mentor (m, j): m es mentor de h desde el conflicto 1 al conflicto 2
> 
> Journey(j, c1, c2) AND ConflictTime(c1,t1) AND ConflictTime(c2,t2)
> AND Hero(h,j) AND Shadow(s,j) AND Guides(m,h,s,t1,t2) -> Mentor(m,j)
> 
> // Base:
> // Encourages (hd,h,s,t1,t2); hd anima a h contra s entre un tiempo t1 y
> un tiempo t2
> //
> // Derivado:
> // Herald(hd,j): hd es un heraldo para el heroe h para su aventura j
> 
> Journey (j,c1,c2) AND Hero(h,j) AND Shadow(s,j) AND
> Encourages(hd,h,s,t1,t2)
> AND ConflictTime(c1,t1) AND ConflictTime (c2, t2)-> Herald (hd,j)
> 
> // Base:
> // Helps (a,h,t1,t2): a ayuda a h entre los momentos t1 y t2
> //
> // Derivado:
> // Allied(a,j): a es un aliado del héroe en la aventura j
> 
> Journey(j,c1,c2) AND Hero(h,j) AND Helps(a, h, t1, t2)
> AND ConflictTime(c1,t1) AND ConflictTime (c2, t2) -> Allied (a, j)
> 
> // Base:
> // Acompanies (sh,h,t1,t2): acompaña al heroe e en entre los momentos t1 y
> t2
> // Tricks(sh,t1,t2); Actua como trickster (será complejo de definir y
> dependerá del mundo)
> //
> // Derivado:
> // Allied(a,j): a es un aliado del héroe en la aventura j
> 
> Journey(j,c1,c2) AND Hero(h,j) AND Acompanies(tr, h, t1, t2)
> AND Tricks(tr,t1,t2)
> AND ConflictTime(c1,t1) AND ConflictTime (c2, t2) -> Trickster (tr, j)
> 
> // Derivado:
> 
> (Mentor(c,j) AND Herald(c,j))
> OR (Mentor(c,j) AND ThresholdGuardian(c,j))
> OR (Mentor(c,j) AND Herald(c,j))
> OR (Mentor(c,j) AND Allied(c,j))
> OR (Mentor(c,j) AND Trickster(c,j))
> OR (Herald(c,j) AND ThresholdGuardian(c,j))
> OR (Herald(c,j) AND Herald(c,j))
> OR (Herald(c,j) AND Allied(c,j))
> OR (Herald(c,j) AND Trickster(c,j))
> OR (ThresholdGuardian(c,j) AND Herald(c,j))
> OR (ThresholdGuardian(c,j) AND Allied(c,j))
> OR (ThresholdGuardian(c,j) AND Trickster(c,j))
> OR (Herald(c,j) AND Allied(c,j))
> OR (Herald(c,j) AND Trickster(c,j))
> OR (Allied(c,j) AND Trickster(c,j)) -> Shapeshifter(c,j)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-GECCO-MADE/issues/9.

## 

JJ

**Comment by mgarenas** [comment]
Uff, me he perdido cuando he llegado a prolog :-)

Creo que estamos generalizando mucho y esta generalización debería ir a 
otro sitio que no fuera un congreso. Quizás es sólo mi impresión.

Maribel

**Comment by mgarenas** [comment]
Yo ya he dicho que lo veo lioso en general, pero seguramente sea yo.

Maribel

**Comment by rhgarcia** [comment]
Ok @JJ, he usado letras simplemente para mejorar la comprensión, pero no implicando que una h sea por fuerza un héroe, por ejemplo. Si lo ves mejor, lo puedo expresar como indivíduos en plan i_1, i_2, i_3 y usaré un lenguaje lógico formal para los predicados, ligando las variables de manera que se lea "para todo i sub 1, i sub 2 tal que evento...". Ok también a expresarlo todo en base a indivíduos y tiempo. Es cierto que metí el concepto de conflicto y quizá lie un poco ya que e conflicto no es una entidad o agente del sistema sino un predicado más. Gracias!

**Comment by JJ** [comment]
OK.

El 29 de enero de 2015, 18:57, Rubén Héctor notifications@github.com
escribió:

> Ok @JJ https://github.com/JJ, he usado letras simplemente para mejorar
> la comprensión, pero no implicando que una h sea por fuerza un héroe, por
> ejemplo. Si lo ves mejor, lo puedo expresar como indivíduos en plan i_1,
> i_2, i_3 y usaré un lenguaje lógico formal para los predicados, ligando las
> variables de manera que se lea "para todo i sub 1, i sub 2 tal que
> evento...". Ok también a expresarlo todo en base a indivíduos y tiempo. Es
> cierto que metí el concepto de conflicto y quizá lie un poco ya que e
> conflicto no es una entidad o agente del sistema sino un predicado más.
> Gracias!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-GECCO-MADE/issues/9#issuecomment-72072035
> .

## 

JJ

**Comment by amorag** [comment]
Esto me parece una pasada y quizá, como dice Maribel, quizá demasiado para el GECCO.

Yo apuntaría a lo del fitness y/o operadores para promover conflictos (cruce y mutación) para el GECCO y dejar esto para una revista. ;D

Pero bueno, vosotros decidís.

En todo caso, y obviando los posibles fallos de nomenclatura o formulación, me parece muy buen trabajo Rubén. ;)

Necesito leerlo con mucho detenimiento (y sin niñas alrededor) para aportar algo positivo a eso, sorry. 

De: Rubén Héctor [mailto:notifications@github.com] 
Enviado el: jueves, 29 de enero de 2015 2:25
Para: geneura-papers/2015-GECCO-MADE
Asunto: [2015-GECCO-MADE] Archetypes analysis (#9)

Mi idea es ser capaz de definir unos predicados que llamo "Base" o "Primitivas", que deben ser implementados por el mundo virtual, y unos predicados derivados que definirán los arquetipos y que no dependen del mundo. Espero ser capaz de clasificar los mundos virtuales en función de las primitivas que ofrecen, y por lo tanto, de los arquetipos que, en teoría, podrían emerger.

Por ejemplo, analizando los arquetipos más típicos (la famosa referencia a The hero's Journey), he sido capaz de extraer hasta 11 predicados "base" que puede tener el mundo: Conflict(c,h,s), ConflictTime(c,t), Before(t1,t2), JustBefore(t1,t2), Wins(c,w), Bad(c,s), Guides (m,h,s,t1,t2), Encourages (hd,h,s,t1,t2), Helps (a,h,t1,t2), Acompanies (tr,h,t1,t2) y Tricks(tr,t1,t2). (se explican más abajo pero aun tiene que explicarse mucho mejor, esto son solo unas notas).
Si el mundo puede implementar los 6 primeros, ya es capaz de devolver 3 arquetipos. si los implementa todos, podrá devolver los 8 arquetipos. La gracia es que unos predicados dependen de otros, pero todos en esencia dependen de dos predicados base "Conflict" y "Bad", es decir... lo que se considera malo y lo que se considera un conflicto entre dos agentes o elementos (nuestra tesis). Sería bonito incluso representar los predicados en un arbol indicando sus dependencias... los nodos base serían Confict, Bad y algunos predicados (helpers) que ayudan a trabajar con medidas temporales. A partir de ahí vendría un arbol muy simpático. 

Podría hacer lo que he hecho con Hero's Journey, pero con Romeo y Julieta: son 12 tropos según tvtropes. Intuyo que tendría que añadir unas primitivas más para expresar relaciones de parentesco y amor. De nuevo, el conflicto estara constántemente apareciendo. 

Ah, he expresado los predicados de manera muy sencilla, pero no sería complicado pasarlo a un lenguaje lógico como prolog, volcar los logs como predicados y luego implementar las primitivas... de hecho, me llama mucho la atención pero no va a dar tiempo ahora mismo :-(

Bueno, dejo esto aquí para seguir mañana. Si queréis echarle un ojo @fergunet https://github.com/fergunet  y @JJ https://github.com/JJ  admito críticas no destructivas :-)

Mis notas:

Según Vogler, existen los arquetipos:
-   héroe
-   Shadow: Villano, enemigo, el enemigo interior, represiones.
-   Mentor: Guía o principios
-   Heraldo: Persona o evento que llama a la aventura
-   Threshold guardian: obtáculos para la consecución del objetivo, ya sean personajes o emociones
-   Shapeshifter: Cambios reales o percibidos.
-   Trickster: Personajes o elementos que acompañan al héroe. Amigos, personajes que promueven el cambio.
-   Aliados: 

// Base
// Conflict(c,h,s): Hay un conflicto c entre h y s
// ConflictTime(c,t): El conflicto c ocurre en el instante t
// Before(t1,t2): t1 es un momento anterior a t2
// JustBefore(t1,t2): t1 es un momento inmediatamente anterior a t2
// Wins(c,w): w ha ganado el conflicto
// Bad(c,s): s tiene una alineación mala antes de que se produzca el conflicto c
//
// Derivados:
// Jorney(j, c1, c2): j es una aventura que comienza con el conflicto c1 y acaba
// con el conflicto c2 
// Hero(h, j): h es un/a héroe/heroina de una aventura j
// Shadow(s,j): s es shadow de h en la aventura j

Conflict(c1,h,s) AND ConflictTime(c1,t1) AND Wins(c1,s) AND Bad(c1,s)
AND Conflict(c2,h,s) AND ConflictTime(c2,t2) AND Wins(c2,h) AND Bad(c2, s)
AND Before (t1,t2) -> Journey (j,c1,c2) AND Hero(h, j) AND Shadow (s, j)

// Derivado:
// ThresholdGuardian(tg,j): tg es un obstáculo en la aventura j 

Journey(j,c1,c2) AND AND ConflictTime(c1,t1) AND ConflictTime (c2, t2)
AND Conflict(tg,h,s) AND ConflictTime(c,t3)
AND !Shadow(tg,j)
AND Before(t1,t3) AND Before(t3,t2) -> ThresholdGuardian(tg,j)

// Base:
// Guides (m,h,s,t1,t2): m guía a h para vencer a s entre t1 y t2
//
// Derivados:
// Mentor (m, j): m es mentor de h desde el conflicto 1 al conflicto 2 

Journey(j, c1, c2) AND ConflictTime(c1,t1) AND ConflictTime(c2,t2)
AND Hero(h,j) AND Shadow(s,j) AND Guides(m,h,s,t1,t2) -> Mentor(m,j)

// Base:
// Encourages (hd,h,s,t1,t2); hd anima a h contra s entre un tiempo t1 y un tiempo t2
//
// Derivado:
// Herald(hd,j): hd es un heraldo para el heroe h para su aventura j

Journey (j,c1,c2) AND Hero(h,j) AND Shadow(s,j) AND Encourages(hd,h,s,t1,t2) 
AND ConflictTime(c1,t1) AND ConflictTime (c2, t2)-> Herald (hd,j) 

// Base:
// Helps (a,h,t1,t2): a ayuda a h entre los momentos t1 y t2
//
// Derivado:
// Allied(a,j): a es un aliado del héroe en la aventura j

Journey(j,c1,c2) AND Hero(h,j) AND Helps(a, h, t1, t2) 
AND ConflictTime(c1,t1) AND ConflictTime (c2, t2) -> Allied (a, j)

// Base:
// Acompanies (sh,h,t1,t2): acompaña al heroe e en entre los momentos t1 y t2
// Tricks(sh,t1,t2); Actua como trickster (será complejo de definir y dependerá del mundo)
//
// Derivado:
// Allied(a,j): a es un aliado del héroe en la aventura j

Journey(j,c1,c2) AND Hero(h,j) AND Acompanies(tr, h, t1, t2)
AND Tricks(tr,t1,t2) 
AND ConflictTime(c1,t1) AND ConflictTime (c2, t2) -> Trickster (tr, j)

// Derivado:

(Mentor(c,j) AND Herald(c,j))
OR (Mentor(c,j) AND ThresholdGuardian(c,j))
OR (Mentor(c,j) AND Herald(c,j))
OR (Mentor(c,j) AND Allied(c,j))
OR (Mentor(c,j) AND Trickster(c,j))
OR (Herald(c,j) AND ThresholdGuardian(c,j))
OR (Herald(c,j) AND Herald(c,j))
OR (Herald(c,j) AND Allied(c,j))
OR (Herald(c,j) AND Trickster(c,j))
OR (ThresholdGuardian(c,j) AND Herald(c,j))
OR (ThresholdGuardian(c,j) AND Allied(c,j))
OR (ThresholdGuardian(c,j) AND Trickster(c,j))
OR (Herald(c,j) AND Allied(c,j))
OR (Herald(c,j) AND Trickster(c,j))
OR (Allied(c,j) AND Trickster(c,j)) -> Shapeshifter(c,j)

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2015-GECCO-MADE/issues/9 .  https://github.com/notifications/beacon/AC6-WszB3Ii3TBFhRqV0yZtx3NqduUtSks5nmYNkgaJpZM4DYswr.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4273/9015 - Fecha de publicación: 01/28/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4260/1 - Fecha de publicación: 12/18/14
Base de datos de virus interno no está actualizado.

**Comment by JJ** [comment]
Tarde o temprano, lo que comenta Rubén tiene que hacerse: sistematizar la
descripción de mundos a través de arquetipos. Si no da tiempo a probarlos
todos para el GECCO, al menos crear alguno según el nuevo método a ver qué
tal va.

**Comment by JJ** [comment]
Chicos, me gustaría ver un poco de actividad escritora el fin de semana
porque si no no va a haber manera de terminar algo...

El 29 de enero de 2015, 20:22, JJ Merelo jjmerelo@gmail.com escribió:

> Tarde o temprano, lo que comenta Rubén tiene que hacerse: sistematizar la
> descripción de mundos a través de arquetipos. Si no da tiempo a probarlos
> todos para el GECCO, al menos crear alguno según el nuevo método a ver qué
> tal va.

## 

JJ
